export interface Currency {
  code: string;
  name: string;
  flag: string;
  country: string;
}

export const CURRENCIES: Currency[] = [
  {
    code: 'USD',
    name: 'United States Dollar',
    country: 'United States',
    flag: '/images/flags/us.svg',
  },
  {
    code: 'EUR',
    name: 'Euro',
    country: 'Europe',
    flag: '/images/flags/eu.svg',
  },
  {
    code: 'GBP',
    name: 'British Pound',
    country: 'United Kingdom',
    flag: '/images/flags/gb.svg',
  },
  {
    code: 'BDT',
    name: 'Bangladeshi Taka',
    country: 'Bangladesh',
    flag: '/images/flags/bd.svg',
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    country: 'India',
    flag: '/images/flags/in.svg',
  },
  {
    code: 'AED',
    name: 'UAE Dirham',
    country: 'UAE',
    flag: '/images/flags/ae.svg',
  },
  {
    code: 'AFN',
    name: 'Afghan Afghani',
    country: 'Afghanistan',
    flag: '/images/flags/af.svg',
  },
  {
    code: 'ALL',
    name: 'Albanian Lek',
    country: 'Albania',
    flag: '/images/flags/al.svg',
  },
  {
    code: 'AMD',
    name: 'Armenian Dram',
    country: 'Armenia',
    flag: '/images/flags/am.svg',
  },
  {
    code: 'ANG',
    name: 'Netherlands Antillian Guilder',
    country: 'Netherlands Antilles',
    flag: '/images/flags/nl.svg',
  },
  {
    code: 'AOA',
    name: 'Angolan Kwanza',
    country: 'Angola',
    flag: '/images/flags/ao.svg',
  },
  {
    code: 'ARS',
    name: 'Argentine Peso',
    country: 'Argentina',
    flag: '/images/flags/ar.svg',
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    country: 'Australia',
    flag: '/images/flags/au.svg',
  },
  {
    code: 'AWG',
    name: 'Aruban Florin',
    country: 'Aruba',
    flag: '/images/flags/aw.svg',
  },
  {
    code: 'AZN',
    name: 'Azerbaijani Manat',
    country: 'Azerbaijan',
    flag: '/images/flags/az.svg',
  },
  {
    code: 'BAM',
    name: 'Bosnia and Herzegovina Mark',
    country: 'Bosnia',
    flag: '/images/flags/ba.svg',
  },
  {
    code: 'BBD',
    name: 'Barbados Dollar',
    country: 'Barbados',
    flag: '/images/flags/bb.svg',
  },
  {
    code: 'BHD',
    name: 'Bahraini Dinar',
    country: 'Bahrain',
    flag: '/images/flags/bh.svg',
  },
  {
    code: 'BIF',
    name: 'Burundian Franc',
    country: 'Burundi',
    flag: '/images/flags/bi.svg',
  },
  {
    code: 'BMD',
    name: 'Bermudian Dollar',
    country: 'Bermuda',
    flag: '/images/flags/bm.svg',
  },
  {
    code: 'BND',
    name: 'Brunei Dollar',
    country: 'Brunei',
    flag: '/images/flags/bn.svg',
  },
  {
    code: 'BOB',
    name: 'Bolivian Boliviano',
    country: 'Bolivia',
    flag: '/images/flags/bo.svg',
  },
  {
    code: 'BRL',
    name: 'Brazilian Real',
    country: 'Brazil',
    flag: '/images/flags/br.svg',
  },
  {
    code: 'BSD',
    name: 'Bahamian Dollar',
    country: 'Bahamas',
    flag: '/images/flags/bs.svg',
  },
  {
    code: 'BTN',
    name: 'Bhutanese Ngultrum',
    country: 'Bhutan',
    flag: '/images/flags/bt.svg',
  },
  {
    code: 'BWP',
    name: 'Botswana Pula',
    country: 'Botswana',
    flag: '/images/flags/bw.svg',
  },
  {
    code: 'BYN',
    name: 'Belarusian Ruble',
    country: 'Belarus',
    flag: '/images/flags/by.svg',
  },
  {
    code: 'BZD',
    name: 'Belize Dollar',
    country: 'Belize',
    flag: '/images/flags/bz.svg',
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    country: 'Canada',
    flag: '/images/flags/ca.svg',
  },
  {
    code: 'CDF',
    name: 'Congolese Franc',
    country: 'Congo',
    flag: '/images/flags/cd.svg',
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    country: 'Switzerland',
    flag: '/images/flags/ch.svg',
  },
  {
    code: 'CLP',
    name: 'Chilean Peso',
    country: 'Chile',
    flag: '/images/flags/cl.svg',
  },
  {
    code: 'CNY',
    name: 'Chinese Renminbi',
    country: 'China',
    flag: '/images/flags/cn.svg',
  },
  {
    code: 'COP',
    name: 'Colombian Peso',
    country: 'Colombia',
    flag: '/images/flags/co.svg',
  },
  {
    code: 'CRC',
    name: 'Costa Rican Colon',
    country: 'Costa Rica',
    flag: '/images/flags/cr.svg',
  },
  {
    code: 'CUP',
    name: 'Cuban Peso',
    country: 'Cuba',
    flag: '/images/flags/cu.svg',
  },
  {
    code: 'CVE',
    name: 'Cape Verdean Escudo',
    country: 'Cape Verde',
    flag: '/images/flags/cv.svg',
  },
  {
    code: 'CZK',
    name: 'Czech Koruna',
    country: 'Czech Republic',
    flag: '/images/flags/cz.svg',
  },
  {
    code: 'DJF',
    name: 'Djiboutian Franc',
    country: 'Djibouti',
    flag: '/images/flags/dj.svg',
  },
  {
    code: 'DKK',
    name: 'Danish Krone',
    country: 'Denmark',
    flag: '/images/flags/dk.svg',
  },
  {
    code: 'DOP',
    name: 'Dominican Peso',
    country: 'Dominican Republic',
    flag: '/images/flags/do.svg',
  },
  {
    code: 'DZD',
    name: 'Algerian Dinar',
    country: 'Algeria',
    flag: '/images/flags/dz.svg',
  },
  {
    code: 'EGP',
    name: 'Egyptian Pound',
    country: 'Egypt',
    flag: '/images/flags/eg.svg',
  },
  {
    code: 'ERN',
    name: 'Eritrean Nakfa',
    country: 'Eritrea',
    flag: '/images/flags/er.svg',
  },
  {
    code: 'ETB',
    name: 'Ethiopian Birr',
    country: 'Ethiopia',
    flag: '/images/flags/et.svg',
  },
  {
    code: 'FJD',
    name: 'Fiji Dollar',
    country: 'Fiji',
    flag: '/images/flags/fj.svg',
  },
  {
    code: 'FKP',
    name: 'Falkland Islands Pound',
    country: 'Falkland Islands',
    flag: '/images/flags/fk.svg',
  },
  {
    code: 'FOK',
    name: 'Faroese Króna',
    country: 'Faroe Islands',
    flag: '/images/flags/fo.svg',
  },
  {
    code: 'GEL',
    name: 'Georgian Lari',
    country: 'Georgia',
    flag: '/images/flags/ge.svg',
  },
  {
    code: 'GGP',
    name: 'Guernsey Pound',
    country: 'Guernsey',
    flag: '/images/flags/gg.svg',
  },
  {
    code: 'GHS',
    name: 'Ghanaian Cedi',
    country: 'Ghana',
    flag: '/images/flags/gh.svg',
  },
  {
    code: 'GIP',
    name: 'Gibraltar Pound',
    country: 'Gibraltar',
    flag: '/images/flags/gi.svg',
  },
  {
    code: 'GMD',
    name: 'Gambian Dalasi',
    country: 'Gambia',
    flag: '/images/flags/gm.svg',
  },
  {
    code: 'GNF',
    name: 'Guinean Franc',
    country: 'Guinea',
    flag: '/images/flags/gn.svg',
  },
  {
    code: 'GTQ',
    name: 'Guatemalan Quetzal',
    country: 'Guatemala',
    flag: '/images/flags/gt.svg',
  },
  {
    code: 'GYD',
    name: 'Guyanese Dollar',
    country: 'Guyana',
    flag: '/images/flags/gy.svg',
  },
  {
    code: 'HKD',
    name: 'Hong Kong Dollar',
    country: 'Hong Kong',
    flag: '/images/flags/hk.svg',
  },
  {
    code: 'HNL',
    name: 'Honduran Lempira',
    country: 'Honduras',
    flag: '/images/flags/hn.svg',
  },
  {
    code: 'HRK',
    name: 'Croatian Kuna',
    country: 'Croatia',
    flag: '/images/flags/hr.svg',
  },
  {
    code: 'HTG',
    name: 'Haitian Gourde',
    country: 'Haiti',
    flag: '/images/flags/ht.svg',
  },
  {
    code: 'HUF',
    name: 'Hungarian Forint',
    country: 'Hungary',
    flag: '/images/flags/hu.svg',
  },
  {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    country: 'Indonesia',
    flag: '/images/flags/id.svg',
  },
  {
    code: 'ILS',
    name: 'Israeli New Shekel',
    country: 'Israel',
    flag: '/images/flags/il.svg',
  },
  {
    code: 'IMP',
    name: 'Manx Pound',
    country: 'Isle of Man',
    flag: '/images/flags/im.svg',
  },
  {
    code: 'IQD',
    name: 'Iraqi Dinar',
    country: 'Iraq',
    flag: '/images/flags/iq.svg',
  },
  {
    code: 'IRR',
    name: 'Iranian Rial',
    country: 'Iran',
    flag: '/images/flags/ir.svg',
  },
  {
    code: 'ISK',
    name: 'Icelandic Króna',
    country: 'Iceland',
    flag: '/images/flags/is.svg',
  },
  {
    code: 'JEP',
    name: 'Jersey Pound',
    country: 'Jersey',
    flag: '/images/flags/je.svg',
  },
  {
    code: 'JMD',
    name: 'Jamaican Dollar',
    country: 'Jamaica',
    flag: '/images/flags/jm.svg',
  },
  {
    code: 'JOD',
    name: 'Jordanian Dinar',
    country: 'Jordan',
    flag: '/images/flags/jo.svg',
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    country: 'Japan',
    flag: '/images/flags/jp.svg',
  },
  {
    code: 'KES',
    name: 'Kenyan Shilling',
    country: 'Kenya',
    flag: '/images/flags/ke.svg',
  },
  {
    code: 'KGS',
    name: 'Kyrgyzstani Som',
    country: 'Kyrgyzstan',
    flag: '/images/flags/kg.svg',
  },
  {
    code: 'KHR',
    name: 'Cambodian Riel',
    country: 'Cambodia',
    flag: '/images/flags/kh.svg',
  },
  {
    code: 'KID',
    name: 'Kiribati Dollar',
    country: 'Kiribati',
    flag: '/images/flags/ki.svg',
  },
  {
    code: 'KMF',
    name: 'Comorian Franc',
    country: 'Comoros',
    flag: '/images/flags/km.svg',
  },
  {
    code: 'KRW',
    name: 'South Korean Won',
    country: 'South Korea',
    flag: '/images/flags/kr.svg',
  },
  {
    code: 'KWD',
    name: 'Kuwaiti Dinar',
    country: 'Kuwait',
    flag: '/images/flags/kw.svg',
  },
  {
    code: 'KYD',
    name: 'Cayman Islands Dollar',
    country: 'Cayman Islands',
    flag: '/images/flags/ky.svg',
  },
  {
    code: 'KZT',
    name: 'Kazakhstani Tenge',
    country: 'Kazakhstan',
    flag: '/images/flags/kz.svg',
  },
  {
    code: 'LAK',
    name: 'Lao Kip',
    country: 'Laos',
    flag: '/images/flags/la.svg',
  },
  {
    code: 'LBP',
    name: 'Lebanese Pound',
    country: 'Lebanon',
    flag: '/images/flags/lb.svg',
  },
  {
    code: 'LKR',
    name: 'Sri Lanka Rupee',
    country: 'Sri Lanka',
    flag: '/images/flags/lk.svg',
  },
  {
    code: 'LRD',
    name: 'Liberian Dollar',
    country: 'Liberia',
    flag: '/images/flags/lr.svg',
  },
  {
    code: 'LSL',
    name: 'Lesotho Loti',
    country: 'Lesotho',
    flag: '/images/flags/ls.svg',
  },
  {
    code: 'LYD',
    name: 'Libyan Dinar',
    country: 'Libya',
    flag: '/images/flags/ly.svg',
  },
  {
    code: 'MAD',
    name: 'Moroccan Dirham',
    country: 'Morocco',
    flag: '/images/flags/ma.svg',
  },
  {
    code: 'MDL',
    name: 'Moldovan Leu',
    country: 'Moldova',
    flag: '/images/flags/md.svg',
  },
  {
    code: 'MGA',
    name: 'Malagasy Ariary',
    country: 'Madagascar',
    flag: '/images/flags/mg.svg',
  },
  {
    code: 'MKD',
    name: 'Macedonian Denar',
    country: 'North Macedonia',
    flag: '/images/flags/mk.svg',
  },
  {
    code: 'MMK',
    name: 'Burmese Kyat',
    country: 'Myanmar',
    flag: '/images/flags/mm.svg',
  },
  {
    code: 'MNT',
    name: 'Mongolian Tögrög',
    country: 'Mongolia',
    flag: '/images/flags/mn.svg',
  },
  {
    code: 'MOP',
    name: 'Macanese Pataca',
    country: 'Macau',
    flag: '/images/flags/mo.svg',
  },
  {
    code: 'MRU',
    name: 'Mauritanian Ouguiya',
    country: 'Mauritania',
    flag: '/images/flags/mr.svg',
  },
  {
    code: 'MUR',
    name: 'Mauritian Rupee',
    country: 'Mauritius',
    flag: '/images/flags/mu.svg',
  },
  {
    code: 'MVR',
    name: 'Maldivian Rufiyaa',
    country: 'Maldives',
    flag: '/images/flags/mv.svg',
  },
  {
    code: 'MWK',
    name: 'Malawian Kwacha',
    country: 'Malawi',
    flag: '/images/flags/mw.svg',
  },
  {
    code: 'MXN',
    name: 'Mexican Peso',
    country: 'Mexico',
    flag: '/images/flags/mx.svg',
  },
  {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    country: 'Malaysia',
    flag: '/images/flags/my.svg',
  },
  {
    code: 'MZN',
    name: 'Mozambican Metical',
    country: 'Mozambique',
    flag: '/images/flags/mz.svg',
  },
  {
    code: 'NAD',
    name: 'Namibian Dollar',
    country: 'Namibia',
    flag: '/images/flags/na.svg',
  },
  {
    code: 'NGN',
    name: 'Nigerian Naira',
    country: 'Nigeria',
    flag: '/images/flags/ng.svg',
  },
  {
    code: 'NIO',
    name: 'Nicaraguan Córdoba',
    country: 'Nicaragua',
    flag: '/images/flags/ni.svg',
  },
  {
    code: 'NOK',
    name: 'Norwegian Krone',
    country: 'Norway',
    flag: '/images/flags/no.svg',
  },
  {
    code: 'NPR',
    name: 'Nepalese Rupee',
    country: 'Nepal',
    flag: '/images/flags/np.svg',
  },
  {
    code: 'NZD',
    name: 'New Zealand Dollar',
    country: 'New Zealand',
    flag: '/images/flags/nz.svg',
  },
  {
    code: 'OMR',
    name: 'Omani Rial',
    country: 'Oman',
    flag: '/images/flags/om.svg',
  },
  {
    code: 'PAB',
    name: 'Panamanian Balboa',
    country: 'Panama',
    flag: '/images/flags/pa.svg',
  },
  {
    code: 'PEN',
    name: 'Peruvian Sol',
    country: 'Peru',
    flag: '/images/flags/pe.svg',
  },
  {
    code: 'PGK',
    name: 'Papua New Guinean Kina',
    country: 'Papua New Guinea',
    flag: '/images/flags/pg.svg',
  },
  {
    code: 'PHP',
    name: 'Philippine Peso',
    country: 'Philippines',
    flag: '/images/flags/ph.svg',
  },
  {
    code: 'PKR',
    name: 'Pakistani Rupee',
    country: 'Pakistan',
    flag: '/images/flags/pk.svg',
  },
  {
    code: 'PLN',
    name: 'Polish Złoty',
    country: 'Poland',
    flag: '/images/flags/pl.svg',
  },
  {
    code: 'PYG',
    name: 'Paraguayan Guaraní',
    country: 'Paraguay',
    flag: '/images/flags/py.svg',
  },
  {
    code: 'QAR',
    name: 'Qatari Rial',
    country: 'Qatar',
    flag: '/images/flags/qa.svg',
  },
  {
    code: 'RON',
    name: 'Romanian Leu',
    country: 'Romania',
    flag: '/images/flags/ro.svg',
  },
  {
    code: 'RSD',
    name: 'Serbian Dinar',
    country: 'Serbia',
    flag: '/images/flags/rs.svg',
  },
  {
    code: 'RUB',
    name: 'Russian Ruble',
    country: 'Russia',
    flag: '/images/flags/ru.svg',
  },
  {
    code: 'RWF',
    name: 'Rwandan Franc',
    country: 'Rwanda',
    flag: '/images/flags/rw.svg',
  },
  {
    code: 'SAR',
    name: 'Saudi Riyal',
    country: 'Saudi Arabia',
    flag: '/images/flags/sa.svg',
  },
  {
    code: 'SBD',
    name: 'Solomon Islands Dollar',
    country: 'Solomon Islands',
    flag: '/images/flags/sb.svg',
  },
  {
    code: 'SCR',
    name: 'Seychellois Rupee',
    country: 'Seychelles',
    flag: '/images/flags/sc.svg',
  },
  {
    code: 'SDG',
    name: 'Sudanese Pound',
    country: 'Sudan',
    flag: '/images/flags/sd.svg',
  },
  {
    code: 'SEK',
    name: 'Swedish Krona',
    country: 'Sweden',
    flag: '/images/flags/se.svg',
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar',
    country: 'Singapore',
    flag: '/images/flags/sg.svg',
  },
  {
    code: 'SHP',
    name: 'Saint Helena Pound',
    country: 'Saint Helena',
    flag: '/images/flags/sh.svg',
  },
  {
    code: 'SLE',
    name: 'Sierra Leonean Leone',
    country: 'Sierra Leone',
    flag: '/images/flags/sl.svg',
  },
  {
    code: 'SOS',
    name: 'Somali Shilling',
    country: 'Somalia',
    flag: '/images/flags/so.svg',
  },
  {
    code: 'SRD',
    name: 'Surinamese Dollar',
    country: 'Suriname',
    flag: '/images/flags/sr.svg',
  },
  {
    code: 'SSP',
    name: 'South Sudanese Pound',
    country: 'South Sudan',
    flag: '/images/flags/ss.svg',
  },
  {
    code: 'STN',
    name: 'São Tomé and Príncipe Dobra',
    country: 'São Tomé',
    flag: '/images/flags/st.svg',
  },
  {
    code: 'SYP',
    name: 'Syrian Pound',
    country: 'Syria',
    flag: '/images/flags/sy.svg',
  },
  {
    code: 'SZL',
    name: 'Swazi Lilangeni',
    country: 'Eswatini',
    flag: '/images/flags/sz.svg',
  },
  {
    code: 'THB',
    name: 'Thai Baht',
    country: 'Thailand',
    flag: '/images/flags/th.svg',
  },
  {
    code: 'TJS',
    name: 'Tajikistani Somoni',
    country: 'Tajikistan',
    flag: '/images/flags/tj.svg',
  },
  {
    code: 'TMT',
    name: 'Turkmenistan Manat',
    country: 'Turkmenistan',
    flag: '/images/flags/tm.svg',
  },
  {
    code: 'TND',
    name: 'Tunisian Dinar',
    country: 'Tunisia',
    flag: '/images/flags/tn.svg',
  },
  {
    code: 'TOP',
    name: 'Tongan Paʻanga',
    country: 'Tonga',
    flag: '/images/flags/to.svg',
  },
  {
    code: 'TRY',
    name: 'Turkish Lira',
    country: 'Turkey',
    flag: '/images/flags/tr.svg',
  },
  {
    code: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    country: 'Trinidad',
    flag: '/images/flags/tt.svg',
  },
  {
    code: 'TVD',
    name: 'Tuvaluan Dollar',
    country: 'Tuvalu',
    flag: '/images/flags/tv.svg',
  },
  {
    code: 'TWD',
    name: 'New Taiwan Dollar',
    country: 'Taiwan',
    flag: '/images/flags/tw.svg',
  },
  {
    code: 'TZS',
    name: 'Tanzanian Shilling',
    country: 'Tanzania',
    flag: '/images/flags/tz.svg',
  },
  {
    code: 'UAH',
    name: 'Ukrainian Hryvnia',
    country: 'Ukraine',
    flag: '/images/flags/ua.svg',
  },
  {
    code: 'UGX',
    name: 'Ugandan Shilling',
    country: 'Uganda',
    flag: '/images/flags/ug.svg',
  },
  {
    code: 'UYU',
    name: 'Uruguayan Peso',
    country: 'Uruguay',
    flag: '/images/flags/uy.svg',
  },
  {
    code: 'UZS',
    name: 'Uzbekistani Som',
    country: 'Uzbekistan',
    flag: '/images/flags/uz.svg',
  },
  {
    code: 'VES',
    name: 'Venezuelan Bolívar',
    country: 'Venezuela',
    flag: '/images/flags/ve.svg',
  },
  {
    code: 'VND',
    name: 'Vietnamese Đồng',
    country: 'Vietnam',
    flag: '/images/flags/vn.svg',
  },
  {
    code: 'VUV',
    name: 'Vanuatu Vatu',
    country: 'Vanuatu',
    flag: '/images/flags/vu.svg',
  },
  {
    code: 'WST',
    name: 'Samoan Tālā',
    country: 'Samoa',
    flag: '/images/flags/ws.svg',
  },
  {
    code: 'XAF',
    name: 'Central African CFA Franc',
    country: 'Central Africa',
    flag: '/images/flags/cf.svg',
  },
  {
    code: 'XCD',
    name: 'East Caribbean Dollar',
    country: 'East Caribbean',
    flag: '/images/flags/ag.svg',
  },
  {
    code: 'XOF',
    name: 'West African CFA Franc',
    country: 'West Africa',
    flag: '/images/flags/sn.svg',
  },
  {
    code: 'XPF',
    name: 'CFP Franc',
    country: 'French Polynesia',
    flag: '/images/flags/pf.svg',
  },
  {
    code: 'YER',
    name: 'Yemeni Rial',
    country: 'Yemen',
    flag: '/images/flags/ye.svg',
  },
  {
    code: 'ZAR',
    name: 'South African Rand',
    country: 'South Africa',
    flag: '/images/flags/za.svg',
  },
  {
    code: 'ZMW',
    name: 'Zambian Kwacha',
    country: 'Zambia',
    flag: '/images/flags/zm.svg',
  },
  {
    code: 'ZWL',
    name: 'Zimbabwean Dollar',
    country: 'Zimbabwe',
    flag: '/images/flags/zw.svg',
  },
];

export const getCurrencyByCode = (code: string): Currency | undefined =>
  CURRENCIES.find(c => c.code === code);
