export interface Transaction {
  id: string;
  user: string;
  from: string;
  to: string;
  amount: string;
  method: string;
  methodType: 'card' | 'bank' | 'wallet' | 'cash';
  status: 'Completed' | 'Pending' | 'Failed' | 'Refunded';
  time: string;
}

export interface KYCUser {
  name: string;
  email: string;
  date: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  avatar: string;
}

export interface Alert {
  type: 'high' | 'warning' | 'info' | 'success';
  title: string;
  description: string;
  time: string;
}

export interface FraudAlert {
  type: 'high' | 'mediums' | 'medium' | 'low';
  title: string;
  description: string;
  time: string;
}

export const statsData = [
  {
    label: 'Total Transfer Volume',
    value: '$15,812,320',
    change: '+12.5%',
    positive: true,
    color: 'green',
  },
  {
    label: 'Total Transactions',
    value: '24,752',
    change: '+8.3%',
    positive: true,
    color: 'blue',
  },
  {
    label: 'Total Revenue',
    value: '$425,780',
    change: '+15.7%',
    positive: true,
    color: 'purple',
  },
  {
    label: 'Net Profit',
    value: '$235,460',
    change: '+10.2%',
    positive: true,
    color: 'yellow',
  },
  {
    label: 'Active Users',
    value: '8,642',
    change: '+18.6%',
    positive: true,
    color: 'cyan',
  },
  {
    label: 'Pending KYC',
    value: '124',
    change: '-5.2%',
    positive: false,
    color: 'red',
  },
];

export const transactionVolumeData = {
  labels: ['May 6', 'May 7', 'May 8', 'May 9', 'May 10', 'May 11', 'May 12'],
  datasets: [
    {
      label: 'Volume',
      data: [310000, 420000, 380000, 510000, 470000, 620000, 892540],
      borderColor: '#16a34a',
      backgroundColor: 'rgba(22,163,74,0.08)',
      fill: true,
      tension: 0.4,
      pointBackgroundColor: '#16a34a',
      pointRadius: 4,
      pointHoverRadius: 6,
    },
  ],
};

export const transactionStatusData = {
  labels: ['Completed', 'Pending', 'Failed', 'Refunded'],
  datasets: [
    {
      data: [18752, 3124, 1563, 1313],
      backgroundColor: ['#16a34a', '#f59e0b', '#ef4444', '#6366f1'],
      borderWidth: 0,
      hoverOffset: 4,
    },
  ],
};

export const revenueOverviewData = {
  labels: ['May 1', 'May 3', 'May 5', 'May 7', 'May 9', 'May 11', 'May 12'],
  datasets: [
    {
      label: 'Revenue',
      data: [28000, 50000, 22000, 45000, 10000, 58000, 38000],
      backgroundColor: '#16a34a',
      borderRadius: 0,
      borderSkipped: false,
      barPercentage: 0.45,
      categoryPercentage: 0.7,
    },
    {
      label: 'Fees',
      data: [15000, 20000, 30000, 18000, 25000, 22000, 20000],
      backgroundColor: '#86efac',
      borderRadius: 0,
      borderSkipped: false,
      barPercentage: 0.45,
      categoryPercentage: 0.7,
    },
  ],
};

export const recentTransactions: Transaction[] = [
  {
    id: 'TSM123456789',
    user: 'John Doe',
    from: 'USA',
    to: 'Bangladesh',
    amount: '$500.00',
    method: 'Visa Card',
    methodType: 'card',
    status: 'Completed',
    time: '2 min ago',
  },
  {
    id: 'TSM123456788',
    user: 'Ahmed Khan',
    from: 'UK',
    to: 'Bangladesh',
    amount: '$300.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    status: 'Pending',
    time: '10 min ago',
  },
  {
    id: 'TSM123456787',
    user: 'Rashid Ahmed',
    from: 'UAE',
    to: 'Bangladesh',
    amount: '$750.00',
    method: 'Cash Pickup',
    methodType: 'cash',
    status: 'Completed',
    time: '20 min ago',
  },
  {
    id: 'TSM123456786',
    user: 'Salma Begum',
    from: 'Saudi Arabia',
    to: 'BD',
    amount: '$1,000.00',
    method: 'Mobile Wallet',
    methodType: 'wallet',
    status: 'Pending',
    time: '25 min ago',
  },
  {
    id: 'TSM123456785',
    user: 'Imran Hossain',
    from: 'Malaysia',
    to: 'Bangladesh',
    amount: '$200.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    status: 'Failed',
    time: '30 min ago',
  },
];

export const allTransactions: Transaction[] = [
  ...recentTransactions,
  {
    id: 'TSM123456784',
    user: 'Fatima Malik',
    from: 'Canada',
    to: 'Bangladesh',
    amount: '$850.00',
    method: 'Visa Card',
    methodType: 'card',
    status: 'Completed',
    time: '1 hr ago',
  },
  {
    id: 'TSM123456783',
    user: 'Karim Hassan',
    from: 'Germany',
    to: 'Bangladesh',
    amount: '$450.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    status: 'Completed',
    time: '2 hr ago',
  },
  {
    id: 'TSM123456782',
    user: 'Nadia Islam',
    from: 'Australia',
    to: 'Bangladesh',
    amount: '$320.00',
    method: 'Mobile Wallet',
    methodType: 'wallet',
    status: 'Refunded',
    time: '3 hr ago',
  },
  {
    id: 'TSM123456781',
    user: 'Rahim Uddin',
    from: 'Italy',
    to: 'Bangladesh',
    amount: '$600.00',
    method: 'Cash Pickup',
    methodType: 'cash',
    status: 'Pending',
    time: '4 hr ago',
  },
  {
    id: 'TSM123456780',
    user: 'Sadia Akter',
    from: 'France',
    to: 'Bangladesh',
    amount: '$150.00',
    method: 'Visa Card',
    methodType: 'card',
    status: 'Failed',
    time: '5 hr ago',
  },
];

export const kycUsers: KYCUser[] = [
  {
    name: 'MD Arif Hossain',
    email: 'arif@example.com',
    date: 'May 12, 2025',
    status: 'Pending',
    avatar: 'AH',
  },
  {
    name: 'Nusrat Jahan',
    email: 'nusrat@example.com',
    date: 'May 12, 2025',
    status: 'Pending',
    avatar: 'NJ',
  },
  {
    name: 'Kamrul Hasan',
    email: 'kamrul@example.com',
    date: 'May 12, 2025',
    status: 'Pending',
    avatar: 'KH',
  },
  {
    name: 'Farzana Akter',
    email: 'farzana@example.com',
    date: 'May 12, 2025',
    status: 'Pending',
    avatar: 'FA',
  },
];

export const systemAlerts: Alert[] = [
  {
    type: 'high',
    title: 'High Risk Transaction',
    description: 'Transaction TSM123456789 flagged as high risk',
    time: '2 min ago',
  },
  {
    type: 'warning',
    title: 'Large Amount Transfer',
    description: '$25,000 transfer to BD from USA',
    time: '15 min ago',
  },
  {
    type: 'info',
    title: 'KYC Pending',
    description: '124 users pending KYC verification',
    time: '1 hour ago',
  },
  {
    type: 'success',
    title: 'Exchange Rate Updated',
    description: 'USD/BDT rate updated: 110.25',
    time: '2 hours ago',
  },
];

export const fraudAlerts: FraudAlert[] = [
  {
    type: 'high',
    title: 'High Risk Transaction',
    description: 'TRID: TSM123456789',
    time: '2 min ago',
  },
  {
    type: 'medium',
    title: 'Velocity Limit Exceeded',
    description: 'User: john.doe@example.com',
    time: '15 min ago',
  },
  {
    type: 'mediums',
    title: 'Multiple Account Detected',
    description: 'User: ahmed.khan@example.com',
    time: '45 min ago',
  },
  {
    type: 'low',
    title: 'Suspicious Location',
    description: 'User: 192.168.1.45',
    time: '1 hour ago',
  },
];

export const topCorridors = [
  { from: 'USA', to: 'Bangladesh', amount: '$4,258,650', pct: 100 },
  { from: 'UAE', to: 'Bangladesh', amount: '$2,985,420', pct: 70 },
  { from: 'UK', to: 'Bangladesh', amount: '$2,456,800', pct: 58 },
  { from: 'Saudi Arabia', to: 'Bangladesh', amount: '$1,856,540', pct: 44 },
  { from: 'Malaysia', to: 'Bangladesh', amount: '$1,256,780', pct: 30 },
];

export const periodTotals = [
  { label: 'Today', value: '$892,540' },
  { label: 'Yesterday', value: '$745,230' },
  { label: 'This Week', value: '$4,256,540' },
  { label: 'This Month', value: '$15,812,320' },
];

//users

export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  status: 'Verified' | 'Pending' | 'Rejected';
  avatar: string;
  customerId: string;
  joinedDate: string;
  lastLogin: string;
  country: string;
  countryFlag: string;
  kyc: {
    status: 'Verified' | 'Pending' | 'Rejected';
    identityProof: string;
    addressProof: string;
    selfieVerification: string;
    amlScreening: string;
    verifiedOn: string;
  };
  wallets: {
    currency: string;
    flag: string;
    balance: string;
    symbol: string;
  }[];
  quickStats: {
    totalTransactions: number;
    totalSent: string;
    totalReceived: string;
    averageTransaction: string;
    successRate: string;
  };
  recentTransactions: {
    id: string;
    type: string;
    to: string;
    toFlag: string;
    amount: string;
    fee: string;
    status: 'Completed' | 'Pending' | 'Failed' | 'Refunded';
    date: string;
  }[];
  documents: {
    title: string;
    type: string;
    status: 'Verified' | 'Pending' | 'Rejected';
    uploadedOn: string;
    icon: 'passport' | 'bill' | 'selfie';
  }[];
}

export const customersData: Customer[] = [
  {
    id: '1',
    name: 'John Rahman',
    email: 'john.rahman@example.com',
    phone: '+44 7700 900123',
    status: 'Verified',
    avatar: 'JR',
    customerId: 'CUS-25051901',
    joinedDate: 'May 19, 2025',
    lastLogin: 'May 19, 2025 10:30 AM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Verified',
      identityProof: 'Passport',
      addressProof: 'Utility Bill',
      selfieVerification: 'Verified',
      amlScreening: 'Passed',
      verifiedOn: 'May 19, 2025',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£2,450.75', symbol: '£' },
      { currency: 'USD Wallet', flag: '🇺🇸', balance: '$1,280.40', symbol: '$' },
      { currency: 'EUR Wallet', flag: '🇪🇺', balance: '€980.30', symbol: '€' },
      {
        currency: 'BDT Settlement',
        flag: '🇧🇩',
        balance: '৳125,450.00',
        symbol: '৳',
      },
    ],
    quickStats: {
      totalTransactions: 24,
      totalSent: '£15,750.00',
      totalReceived: '£15,210.00',
      averageTransaction: '£656.25',
      successRate: '95.8%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051901',
        type: 'Send Money',
        to: 'Bangladesh',
        toFlag: '🇧🇩',
        amount: '£520.00',
        fee: '£3.50',
        status: 'Completed',
        date: 'May 19, 2025',
      },
      {
        id: 'TXN-25051890',
        type: 'Send Money',
        to: 'India',
        toFlag: '🇮🇳',
        amount: '£750.00',
        fee: '£4.00',
        status: 'Completed',
        date: 'May 18, 2025',
      },
      {
        id: 'TXN-25051875',
        type: 'Send Money',
        to: 'Pakistan',
        toFlag: '🇵🇰',
        amount: '£320.00',
        fee: '£2.50',
        status: 'Completed',
        date: 'May 17, 2025',
      },
      {
        id: 'TXN-25051860',
        type: 'Top Up',
        to: 'GBP Wallet',
        toFlag: '🇬🇧',
        amount: '£500.00',
        fee: '£0.00',
        status: 'Completed',
        date: 'May 16, 2025',
      },
      {
        id: 'TXN-25051845',
        type: 'Withdraw',
        to: 'Bank Transfer',
        toFlag: '🏦',
        amount: '£300.00',
        fee: '£1.50',
        status: 'Completed',
        date: 'May 15, 2025',
      },
    ],
    documents: [
      {
        title: 'Passport',
        type: 'ID Proof',
        status: 'Verified',
        uploadedOn: 'May 19, 2025',
        icon: 'passport',
      },
      {
        title: 'Utility Bill',
        type: 'Address Proof',
        status: 'Verified',
        uploadedOn: 'May 19, 2025',
        icon: 'bill',
      },
      {
        title: 'Selfie',
        type: 'Selfie Verification',
        status: 'Verified',
        uploadedOn: 'May 19, 2025',
        icon: 'selfie',
      },
    ],
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '+44 7700 900124',
    status: 'Pending',
    avatar: 'PS',
    customerId: 'CUS-25051902',
    joinedDate: 'May 18, 2025',
    lastLogin: 'May 18, 2025 03:15 PM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Pending',
      identityProof: 'National ID',
      addressProof: 'Bank Statement',
      selfieVerification: 'Pending',
      amlScreening: 'In Progress',
      verifiedOn: '—',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£850.20', symbol: '£' },
      {
        currency: 'INR Wallet',
        flag: '🇮🇳',
        balance: '₹45,200.00',
        symbol: '₹',
      },
    ],
    quickStats: {
      totalTransactions: 8,
      totalSent: '£3,200.00',
      totalReceived: '£3,050.00',
      averageTransaction: '£400.00',
      successRate: '87.5%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051810',
        type: 'Send Money',
        to: 'India',
        toFlag: '🇮🇳',
        amount: '£420.00',
        fee: '£3.00',
        status: 'Pending',
        date: 'May 18, 2025',
      },
      {
        id: 'TXN-25051795',
        type: 'Top Up',
        to: 'GBP Wallet',
        toFlag: '🇬🇧',
        amount: '£200.00',
        fee: '£0.00',
        status: 'Completed',
        date: 'May 17, 2025',
      },
    ],
    documents: [
      {
        title: 'National ID',
        type: 'ID Proof',
        status: 'Pending',
        uploadedOn: 'May 18, 2025',
        icon: 'passport',
      },
      {
        title: 'Bank Statement',
        type: 'Address Proof',
        status: 'Pending',
        uploadedOn: 'May 18, 2025',
        icon: 'bill',
      },
    ],
  },
  {
    id: '3',
    name: 'Ahmed Khan',
    email: 'ahmed.khan@example.com',
    phone: '+44 7700 900125',
    status: 'Verified',
    avatar: 'AK',
    customerId: 'CUS-25051903',
    joinedDate: 'May 15, 2025',
    lastLogin: 'May 19, 2025 08:45 AM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Verified',
      identityProof: 'Passport',
      addressProof: 'Council Tax Bill',
      selfieVerification: 'Verified',
      amlScreening: 'Passed',
      verifiedOn: 'May 15, 2025',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£5,120.60', symbol: '£' },
      { currency: 'USD Wallet', flag: '🇺🇸', balance: '$2,800.00', symbol: '$' },
      {
        currency: 'PKR Wallet',
        flag: '🇵🇰',
        balance: '₨180,000.00',
        symbol: '₨',
      },
    ],
    quickStats: {
      totalTransactions: 42,
      totalSent: '£28,500.00',
      totalReceived: '£27,900.00',
      averageTransaction: '£678.57',
      successRate: '97.6%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051920',
        type: 'Send Money',
        to: 'Pakistan',
        toFlag: '🇵🇰',
        amount: '£1,200.00',
        fee: '£5.00',
        status: 'Completed',
        date: 'May 19, 2025',
      },
      {
        id: 'TXN-25051905',
        type: 'Send Money',
        to: 'Bangladesh',
        toFlag: '🇧🇩',
        amount: '£680.00',
        fee: '£3.50',
        status: 'Completed',
        date: 'May 18, 2025',
      },
      {
        id: 'TXN-25051888',
        type: 'Withdraw',
        to: 'Bank Transfer',
        toFlag: '🏦',
        amount: '£500.00',
        fee: '£2.00',
        status: 'Completed',
        date: 'May 17, 2025',
      },
    ],
    documents: [
      {
        title: 'Passport',
        type: 'ID Proof',
        status: 'Verified',
        uploadedOn: 'May 15, 2025',
        icon: 'passport',
      },
      {
        title: 'Council Tax Bill',
        type: 'Address Proof',
        status: 'Verified',
        uploadedOn: 'May 15, 2025',
        icon: 'bill',
      },
      {
        title: 'Selfie',
        type: 'Selfie Verification',
        status: 'Verified',
        uploadedOn: 'May 15, 2025',
        icon: 'selfie',
      },
    ],
  },
  {
    id: '4',
    name: 'Maria Santos',
    email: 'maria.santos@example.com',
    phone: '+44 7700 900126',
    status: 'Verified',
    avatar: 'MS',
    customerId: 'CUS-25051904',
    joinedDate: 'May 10, 2025',
    lastLogin: 'May 19, 2025 11:20 AM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Verified',
      identityProof: 'Driving License',
      addressProof: 'Utility Bill',
      selfieVerification: 'Verified',
      amlScreening: 'Passed',
      verifiedOn: 'May 10, 2025',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£3,780.45', symbol: '£' },
      { currency: 'EUR Wallet', flag: '🇪🇺', balance: '€1,450.00', symbol: '€' },
      {
        currency: 'PHP Wallet',
        flag: '🇵🇭',
        balance: '₱95,000.00',
        symbol: '₱',
      },
    ],
    quickStats: {
      totalTransactions: 31,
      totalSent: '£18,200.00',
      totalReceived: '£17,600.00',
      averageTransaction: '£587.10',
      successRate: '93.5%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051930',
        type: 'Send Money',
        to: 'Philippines',
        toFlag: '🇵🇭',
        amount: '£950.00',
        fee: '£4.50',
        status: 'Completed',
        date: 'May 19, 2025',
      },
      {
        id: 'TXN-25051915',
        type: 'Top Up',
        to: 'GBP Wallet',
        toFlag: '🇬🇧',
        amount: '£1,000.00',
        fee: '£0.00',
        status: 'Completed',
        date: 'May 18, 2025',
      },
      {
        id: 'TXN-25051900',
        type: 'Send Money',
        to: 'Philippines',
        toFlag: '🇵🇭',
        amount: '£620.00',
        fee: '£3.50',
        status: 'Failed',
        date: 'May 17, 2025',
      },
    ],
    documents: [
      {
        title: 'Driving License',
        type: 'ID Proof',
        status: 'Verified',
        uploadedOn: 'May 10, 2025',
        icon: 'passport',
      },
      {
        title: 'Utility Bill',
        type: 'Address Proof',
        status: 'Verified',
        uploadedOn: 'May 10, 2025',
        icon: 'bill',
      },
      {
        title: 'Selfie',
        type: 'Selfie Verification',
        status: 'Verified',
        uploadedOn: 'May 10, 2025',
        icon: 'selfie',
      },
    ],
  },
  {
    id: '5',
    name: 'James Okafor',
    email: 'james.okafor@example.com',
    phone: '+44 7700 900127',
    status: 'Rejected',
    avatar: 'JO',
    customerId: 'CUS-25051905',
    joinedDate: 'May 8, 2025',
    lastLogin: 'May 12, 2025 02:00 PM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Rejected',
      identityProof: 'Rejected',
      addressProof: 'Rejected',
      selfieVerification: 'Failed',
      amlScreening: 'Failed',
      verifiedOn: '—',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£0.00', symbol: '£' },
    ],
    quickStats: {
      totalTransactions: 2,
      totalSent: '£0.00',
      totalReceived: '£0.00',
      averageTransaction: '£0.00',
      successRate: '0%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051820',
        type: 'Top Up',
        to: 'GBP Wallet',
        toFlag: '🇬🇧',
        amount: '£100.00',
        fee: '£0.00',
        status: 'Failed',
        date: 'May 8, 2025',
      },
    ],
    documents: [
      {
        title: 'Passport',
        type: 'ID Proof',
        status: 'Rejected',
        uploadedOn: 'May 8, 2025',
        icon: 'passport',
      },
    ],
  },
  {
    id: '6',
    name: 'Fatima Ali',
    email: 'fatima.ali@example.com',
    phone: '+44 7700 900128',
    status: 'Pending',
    avatar: 'FA',
    customerId: 'CUS-25051906',
    joinedDate: 'May 17, 2025',
    lastLogin: 'May 19, 2025 09:05 AM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Pending',
      identityProof: 'Passport',
      addressProof: 'Pending',
      selfieVerification: 'Pending',
      amlScreening: 'In Progress',
      verifiedOn: '—',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£1,200.00', symbol: '£' },
      { currency: 'USD Wallet', flag: '🇺🇸', balance: '$450.00', symbol: '$' },
    ],
    quickStats: {
      totalTransactions: 5,
      totalSent: '£2,100.00',
      totalReceived: '£2,000.00',
      averageTransaction: '£420.00',
      successRate: '80.0%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051940',
        type: 'Send Money',
        to: 'Bangladesh',
        toFlag: '🇧🇩',
        amount: '£380.00',
        fee: '£2.50',
        status: 'Pending',
        date: 'May 19, 2025',
      },
    ],
    documents: [
      {
        title: 'Passport',
        type: 'ID Proof',
        status: 'Verified',
        uploadedOn: 'May 17, 2025',
        icon: 'passport',
      },
      {
        title: 'Utility Bill',
        type: 'Address Proof',
        status: 'Pending',
        uploadedOn: 'May 17, 2025',
        icon: 'bill',
      },
    ],
  },
  {
    id: '7',
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    phone: '+44 7700 900129',
    status: 'Verified',
    avatar: 'DW',
    customerId: 'CUS-25051907',
    joinedDate: 'Apr 30, 2025',
    lastLogin: 'May 19, 2025 07:30 AM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Verified',
      identityProof: 'Passport',
      addressProof: 'Bank Statement',
      selfieVerification: 'Verified',
      amlScreening: 'Passed',
      verifiedOn: 'Apr 30, 2025',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£8,900.00', symbol: '£' },
      { currency: 'USD Wallet', flag: '🇺🇸', balance: '$4,200.00', symbol: '$' },
      { currency: 'EUR Wallet', flag: '🇪🇺', balance: '€2,100.00', symbol: '€' },
    ],
    quickStats: {
      totalTransactions: 68,
      totalSent: '£52,300.00',
      totalReceived: '£51,100.00',
      averageTransaction: '£769.12',
      successRate: '98.5%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051950',
        type: 'Send Money',
        to: 'India',
        toFlag: '🇮🇳',
        amount: '£2,000.00',
        fee: '£6.00',
        status: 'Completed',
        date: 'May 19, 2025',
      },
      {
        id: 'TXN-25051935',
        type: 'Send Money',
        to: 'Nigeria',
        toFlag: '🇳🇬',
        amount: '£1,500.00',
        fee: '£5.50',
        status: 'Completed',
        date: 'May 18, 2025',
      },
      {
        id: 'TXN-25051920',
        type: 'Withdraw',
        to: 'Bank Transfer',
        toFlag: '🏦',
        amount: '£3,000.00',
        fee: '£5.00',
        status: 'Completed',
        date: 'May 17, 2025',
      },
    ],
    documents: [
      {
        title: 'Passport',
        type: 'ID Proof',
        status: 'Verified',
        uploadedOn: 'Apr 30, 2025',
        icon: 'passport',
      },
      {
        title: 'Bank Statement',
        type: 'Address Proof',
        status: 'Verified',
        uploadedOn: 'Apr 30, 2025',
        icon: 'bill',
      },
      {
        title: 'Selfie',
        type: 'Selfie Verification',
        status: 'Verified',
        uploadedOn: 'Apr 30, 2025',
        icon: 'selfie',
      },
    ],
  },
  {
    id: '8',
    name: 'Sophie Martin',
    email: 'sophie.martin@example.com',
    phone: '+44 7700 900130',
    status: 'Verified',
    avatar: 'SM',
    customerId: 'CUS-25051908',
    joinedDate: 'May 5, 2025',
    lastLogin: 'May 19, 2025 12:00 PM',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    kyc: {
      status: 'Verified',
      identityProof: 'Driving License',
      addressProof: 'Council Tax Bill',
      selfieVerification: 'Verified',
      amlScreening: 'Passed',
      verifiedOn: 'May 5, 2025',
    },
    wallets: [
      { currency: 'GBP Wallet', flag: '🇬🇧', balance: '£4,350.80', symbol: '£' },
      { currency: 'EUR Wallet', flag: '🇪🇺', balance: '€2,800.00', symbol: '€' },
    ],
    quickStats: {
      totalTransactions: 19,
      totalSent: '£11,400.00',
      totalReceived: '£11,100.00',
      averageTransaction: '£600.00',
      successRate: '94.7%',
    },
    recentTransactions: [
      {
        id: 'TXN-25051960',
        type: 'Send Money',
        to: 'France',
        toFlag: '🇫🇷',
        amount: '£780.00',
        fee: '£3.50',
        status: 'Completed',
        date: 'May 19, 2025',
      },
      {
        id: 'TXN-25051945',
        type: 'Top Up',
        to: 'GBP Wallet',
        toFlag: '🇬🇧',
        amount: '£1,500.00',
        fee: '£0.00',
        status: 'Completed',
        date: 'May 18, 2025',
      },
    ],
    documents: [
      {
        title: 'Driving License',
        type: 'ID Proof',
        status: 'Verified',
        uploadedOn: 'May 5, 2025',
        icon: 'passport',
      },
      {
        title: 'Council Tax Bill',
        type: 'Address Proof',
        status: 'Verified',
        uploadedOn: 'May 5, 2025',
        icon: 'bill',
      },
      {
        title: 'Selfie',
        type: 'Selfie Verification',
        status: 'Verified',
        uploadedOn: 'May 5, 2025',
        icon: 'selfie',
      },
    ],
  },
];

//all transitions


export type TxStatus = 'Completed' | 'Pending' | 'Failed' | 'Refunded';
export type TxMethod =
  | 'Visa Card'
  | 'Mastercard'
  | 'Bank Transfer'
  | 'Cash Pickup'
  | 'Mobile Wallet'
  | 'bKash'
  | 'Nagad';
export type TxMethodType = 'card' | 'bank' | 'cash' | 'wallet';

export interface TxSender {
  name: string;
  email: string;
  avatar: string;
  country: string;
  flag: string;
  phone: string;
}

export interface TxReceiver {
  name: string;
  country: string;
  flag: string;
  phone: string;
}

export interface TxTimeline {
  label: string;
  date: string;
  time: string;
}

export interface AllTransaction {
  id: string;
  sender: TxSender;
  receiver: TxReceiver;
  amount: string;
  amountLocal: string;
  fee: string;
  exchangeRate: string;
  totalDebit: string;
  method: TxMethod;
  methodType: TxMethodType;
  purpose: string;
  status: TxStatus;
  date: string;
  time: string;
  timeAgo: string;
  timeline: TxTimeline[];
}

export const txStatCards = [
  {
    label: 'Total Transactions',
    value: '24,752',
    change: '+12.5% from last week',
    positive: true,
    icon: '≡',
    color: '#2563eb',
    sparkColor: '#3b82f6',
    spark: [18, 12, 22, 10, 20, 8, 15, 6, 18, 4],
  },
  {
    label: 'Completed',
    value: '18,752',
    change: '+10.2% from last week',
    positive: true,
    icon: '✓',
    color: '#16a34a',
    sparkColor: '#22c55e',
    spark: [5, 10, 8, 15, 12, 20, 18, 22, 19, 25],
  },
  {
    label: 'Pending',
    value: '3,124',
    change: '+8.3% from last week',
    positive: true,
    icon: '⏱',
    color: '#f59e0b',
    sparkColor: '#fbbf24',
    spark: [10, 8, 12, 9, 14, 11, 15, 10, 13, 12],
  },
  {
    label: 'Failed',
    value: '1,583',
    change: '-5.6% from last week',
    positive: false,
    icon: '✕',
    color: '#ef4444',
    sparkColor: '#f87171',
    spark: [14, 12, 10, 13, 9, 11, 8, 10, 7, 9],
  },
  {
    label: 'Refunded',
    value: '1,313',
    change: '+3.1% from last week',
    positive: true,
    icon: '↺',
    color: '#8b5cf6',
    sparkColor: '#a78bfa',
    spark: [4, 6, 5, 8, 6, 9, 7, 10, 8, 11],
  },
];

export const allTransactionsData: AllTransaction[] = [
  // ── Page 1 ───────────────────────────────────────────────────────────────
  {
    id: 'TXN-2505124789',
    sender: {
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'JD',
      country: 'United Kingdom',
      flag: '🇬🇧',
      phone: '+44 7700 900123',
    },
    receiver: {
      name: 'Rahim Uddin',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1712 345678',
    },
    amount: '£500.00',
    amountLocal: '৳72,500.00',
    fee: '£3.50',
    exchangeRate: '1 GBP = ৳145.00',
    totalDebit: '£503.50',
    method: 'Visa Card',
    methodType: 'card',
    purpose: 'Family Support',
    status: 'Completed',
    date: 'May 12, 2025',
    time: '2:32 PM',
    timeAgo: '2 min ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '2:31 PM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '2:31 PM' },
      { label: 'Processing', date: 'May 12, 2025', time: '2:31 PM' },
      { label: 'Completed', date: 'May 12, 2025', time: '2:32 PM' },
    ],
  },
  {
    id: 'TXN-2505124788',
    sender: {
      name: 'Ahmed Khan',
      email: 'ahmed.khan@example.com',
      avatar: 'AK',
      country: 'United Kingdom',
      flag: '🇬🇧',
      phone: '+44 7700 900125',
    },
    receiver: {
      name: 'Maria Santos',
      country: 'Philippines',
      flag: '🇵🇭',
      phone: '+63 917 123 4567',
    },
    amount: '£300.00',
    amountLocal: '₱16,800.00',
    fee: '£2.50',
    exchangeRate: '1 GBP = ₱56.00',
    totalDebit: '£302.50',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Education',
    status: 'Pending',
    date: 'May 12, 2025',
    time: '2:22 PM',
    timeAgo: '10 min ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '2:22 PM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '2:23 PM' },
    ],
  },
  {
    id: 'TXN-2505124787',
    sender: {
      name: 'Rashid Ahmed',
      email: 'rashid.ahmed@example.com',
      avatar: 'RA',
      country: 'UAE',
      flag: '🇦🇪',
      phone: '+971 50 123 4567',
    },
    receiver: {
      name: 'Sabbir Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1812 345678',
    },
    amount: '£750.00',
    amountLocal: '৳91,500.00',
    fee: '£4.50',
    exchangeRate: '1 GBP = ৳122.00',
    totalDebit: '£754.50',
    method: 'Cash Pickup',
    methodType: 'cash',
    purpose: 'Medical',
    status: 'Completed',
    date: 'May 12, 2025',
    time: '2:12 PM',
    timeAgo: '20 min ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '2:10 PM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '2:11 PM' },
      { label: 'Processing', date: 'May 12, 2025', time: '2:11 PM' },
      { label: 'Completed', date: 'May 12, 2025', time: '2:12 PM' },
    ],
  },
  {
    id: 'TXN-2505124786',
    sender: {
      name: 'Sarina Begum',
      email: 'sarina.begum@example.com',
      avatar: 'SB',
      country: 'Saudi Arabia',
      flag: '🇸🇦',
      phone: '+966 50 123 4567',
    },
    receiver: {
      name: 'Mohammad Ali',
      country: 'India',
      flag: '🇮🇳',
      phone: '+91 98765 43210',
    },
    amount: '£1,000.00',
    amountLocal: '₹83,200.00',
    fee: '£5.00',
    exchangeRate: '1 GBP = ₹83.20',
    totalDebit: '£1,005.00',
    method: 'Mobile Wallet',
    methodType: 'wallet',
    purpose: 'Business',
    status: 'Pending',
    date: 'May 12, 2025',
    time: '2:07 PM',
    timeAgo: '25 min ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '2:07 PM' },
    ],
  },
  {
    id: 'TXN-2505124785',
    sender: {
      name: 'Imran Hossain',
      email: 'imran.hossain@example.com',
      avatar: 'IH',
      country: 'Malaysia',
      flag: '🇲🇾',
      phone: '+60 12 345 6789',
    },
    receiver: {
      name: 'Arif Khan',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1912 345678',
    },
    amount: '£200.00',
    amountLocal: '৳18,200.00',
    fee: '£2.00',
    exchangeRate: '1 GBP = ৳91.00',
    totalDebit: '£202.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Personal',
    status: 'Failed',
    date: 'May 12, 2025',
    time: '2:02 PM',
    timeAgo: '30 min ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '2:02 PM' },
      { label: 'Payment Failed', date: 'May 12, 2025', time: '2:03 PM' },
    ],
  },
  {
    id: 'TXN-2505124784',
    sender: {
      name: 'Fatima Ali',
      email: 'fatima.ali@example.com',
      avatar: 'FA',
      country: 'United Kingdom',
      flag: '🇬🇧',
      phone: '+44 7700 900128',
    },
    receiver: {
      name: 'Nusrat Jahan',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1612 345678',
    },
    amount: '£150.00',
    amountLocal: '৳21,750.00',
    fee: '£1.50',
    exchangeRate: '1 GBP = ৳145.00',
    totalDebit: '£151.50',
    method: 'bKash',
    methodType: 'wallet',
    purpose: 'Family Support',
    status: 'Completed',
    date: 'May 12, 2025',
    time: '1:47 PM',
    timeAgo: '45 min ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '1:45 PM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '1:46 PM' },
      { label: 'Completed', date: 'May 12, 2025', time: '1:47 PM' },
    ],
  },
  {
    id: 'TXN-2505124783',
    sender: {
      name: 'David Wilson',
      email: 'david.wilson@example.com',
      avatar: 'DW',
      country: 'United Kingdom',
      flag: '🇬🇧',
      phone: '+44 7700 900129',
    },
    receiver: {
      name: 'Sujon Das',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1512 345678',
    },
    amount: '£250.00',
    amountLocal: '৳36,500.00',
    fee: '£2.50',
    exchangeRate: '1 GBP = ৳146.00',
    totalDebit: '£252.50',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Education',
    status: 'Refunded',
    date: 'May 12, 2025',
    time: '1:32 PM',
    timeAgo: '1 hour ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '1:30 PM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '1:31 PM' },
      { label: 'Refunded', date: 'May 12, 2025', time: '1:32 PM' },
    ],
  },
  {
    id: 'TXN-2505124782',
    sender: {
      name: 'Sophie Martin',
      email: 'sophie.martin@example.com',
      avatar: 'SM',
      country: 'United Kingdom',
      flag: '🇬🇧',
      phone: '+44 7700 900130',
    },
    receiver: {
      name: 'Tanvir Hasan',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1412 345678',
    },
    amount: '£400.00',
    amountLocal: '৳58,400.00',
    fee: '£3.00',
    exchangeRate: '1 GBP = ৳146.00',
    totalDebit: '£403.00',
    method: 'Nagad',
    methodType: 'wallet',
    purpose: 'Medical',
    status: 'Completed',
    date: 'May 12, 2025',
    time: '1:32 PM',
    timeAgo: '1 hour ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '1:30 PM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '1:31 PM' },
      { label: 'Completed', date: 'May 12, 2025', time: '1:32 PM' },
    ],
  },
  {
    id: 'TXN-2505124781',
    sender: {
      name: 'James Okafor',
      email: 'james.okafor@example.com',
      avatar: 'JO',
      country: 'UAE',
      flag: '🇦🇪',
      phone: '+971 55 987 6543',
    },
    receiver: {
      name: 'Ibrahim Khalil',
      country: 'UAE',
      flag: '🇦🇪',
      phone: '+971 50 876 5432',
    },
    amount: 'AED 1,200.00',
    amountLocal: '৳36,000.00',
    fee: 'AED 6.00',
    exchangeRate: '1 AED = ৳30.00',
    totalDebit: 'AED 1,206.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Business',
    status: 'Completed',
    date: 'May 12, 2025',
    time: '1:32 PM',
    timeAgo: '1 hour ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '1:30 PM' },
      { label: 'Completed', date: 'May 12, 2025', time: '1:32 PM' },
    ],
  },
  {
    id: 'TXN-2505124780',
    sender: {
      name: 'Priya Sharma',
      email: 'priya.sharma@example.com',
      avatar: 'PS',
      country: 'United Kingdom',
      flag: '🇬🇧',
      phone: '+44 7700 900124',
    },
    receiver: {
      name: 'Shakil Ahmed',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1312 345678',
    },
    amount: '$600.00',
    amountLocal: '৳54,600.00',
    fee: '$3.50',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$603.50',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Family Support',
    status: 'Pending',
    date: 'May 12, 2025',
    time: '12:32 PM',
    timeAgo: '2 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '12:32 PM' },
    ],
  },
  // ── Page 2 ───────────────────────────────────────────────────────────────
  {
    id: 'TXN-2505124779',
    sender: {
      name: 'Karim Hassan',
      email: 'karim.hassan@example.com',
      avatar: 'KH',
      country: 'Germany',
      flag: '🇩🇪',
      phone: '+49 170 123 4567',
    },
    receiver: {
      name: 'Rubel Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1711 234567',
    },
    amount: '€450.00',
    amountLocal: '৳53,550.00',
    fee: '€3.00',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€453.00',
    method: 'Visa Card',
    methodType: 'card',
    purpose: 'Family Support',
    status: 'Completed',
    date: 'May 12, 2025',
    time: '11:55 AM',
    timeAgo: '3 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '11:53 AM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '11:54 AM' },
      { label: 'Completed', date: 'May 12, 2025', time: '11:55 AM' },
    ],
  },
  {
    id: 'TXN-2505124778',
    sender: {
      name: 'Nadia Islam',
      email: 'nadia.islam@example.com',
      avatar: 'NI',
      country: 'Australia',
      flag: '🇦🇺',
      phone: '+61 412 345 678',
    },
    receiver: {
      name: 'Kamal Uddin',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1811 234567',
    },
    amount: 'AUD 320.00',
    amountLocal: '৳23,040.00',
    fee: 'AUD 2.00',
    exchangeRate: '1 AUD = ৳72.00',
    totalDebit: 'AUD 322.00',
    method: 'Mobile Wallet',
    methodType: 'wallet',
    purpose: 'Medical',
    status: 'Refunded',
    date: 'May 12, 2025',
    time: '11:20 AM',
    timeAgo: '3 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '11:18 AM' },
      { label: 'Payment Confirmed', date: 'May 12, 2025', time: '11:19 AM' },
      { label: 'Refunded', date: 'May 12, 2025', time: '11:20 AM' },
    ],
  },
  {
    id: 'TXN-2505124777',
    sender: {
      name: 'Rahim Uddin',
      email: 'rahim.uddin2@example.com',
      avatar: 'RU',
      country: 'Italy',
      flag: '🇮🇹',
      phone: '+39 320 123 4567',
    },
    receiver: {
      name: 'Selim Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1911 234567',
    },
    amount: '€600.00',
    amountLocal: '৳71,400.00',
    fee: '€4.00',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€604.00',
    method: 'Cash Pickup',
    methodType: 'cash',
    purpose: 'Personal',
    status: 'Pending',
    date: 'May 12, 2025',
    time: '10:45 AM',
    timeAgo: '4 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '10:45 AM' },
    ],
  },
  {
    id: 'TXN-2505124776',
    sender: {
      name: 'Sadia Akter',
      email: 'sadia.akter@example.com',
      avatar: 'SA',
      country: 'France',
      flag: '🇫🇷',
      phone: '+33 6 12 34 56 78',
    },
    receiver: {
      name: 'Milon Das',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1611 234567',
    },
    amount: '€150.00',
    amountLocal: '৳17,850.00',
    fee: '€1.50',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€151.50',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Education',
    status: 'Failed',
    date: 'May 12, 2025',
    time: '10:10 AM',
    timeAgo: '5 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 12, 2025', time: '10:10 AM' },
      { label: 'Payment Failed', date: 'May 12, 2025', time: '10:11 AM' },
    ],
  },
  {
    id: 'TXN-2505124775',
    sender: {
      name: 'Fatima Malik',
      email: 'fatima.malik@example.com',
      avatar: 'FM',
      country: 'Canada',
      flag: '🇨🇦',
      phone: '+1 416 555 0123',
    },
    receiver: {
      name: 'Jamal Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1511 234567',
    },
    amount: 'CAD 850.00',
    amountLocal: '৳68,000.00',
    fee: 'CAD 5.00',
    exchangeRate: '1 CAD = ৳80.00',
    totalDebit: 'CAD 855.00',
    method: 'Visa Card',
    methodType: 'card',
    purpose: 'Business',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '9:30 PM',
    timeAgo: '5 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '9:28 PM' },
      { label: 'Payment Confirmed', date: 'May 11, 2025', time: '9:29 PM' },
      { label: 'Completed', date: 'May 11, 2025', time: '9:30 PM' },
    ],
  },
  {
    id: 'TXN-2505124774',
    sender: {
      name: 'Omar Sheikh',
      email: 'omar.sheikh@example.com',
      avatar: 'OS',
      country: 'Saudi Arabia',
      flag: '🇸🇦',
      phone: '+966 55 234 5678',
    },
    receiver: {
      name: 'Nurul Islam',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1411 234567',
    },
    amount: 'SAR 1,500.00',
    amountLocal: '৳45,000.00',
    fee: 'SAR 8.00',
    exchangeRate: '1 SAR = ৳30.00',
    totalDebit: 'SAR 1,508.00',
    method: 'bKash',
    methodType: 'wallet',
    purpose: 'Family Support',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '8:15 PM',
    timeAgo: '6 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '8:13 PM' },
      { label: 'Payment Confirmed', date: 'May 11, 2025', time: '8:14 PM' },
      { label: 'Completed', date: 'May 11, 2025', time: '8:15 PM' },
    ],
  },
  {
    id: 'TXN-2505124773',
    sender: {
      name: 'Ling Wei',
      email: 'ling.wei@example.com',
      avatar: 'LW',
      country: 'Malaysia',
      flag: '🇲🇾',
      phone: '+60 16 234 5678',
    },
    receiver: {
      name: 'Rasel Ahmed',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1311 234567',
    },
    amount: 'MYR 900.00',
    amountLocal: '৳22,500.00',
    fee: 'MYR 5.00',
    exchangeRate: '1 MYR = ৳25.00',
    totalDebit: 'MYR 905.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Medical',
    status: 'Pending',
    date: 'May 11, 2025',
    time: '7:45 PM',
    timeAgo: '7 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '7:45 PM' },
    ],
  },
  {
    id: 'TXN-2505124772',
    sender: {
      name: 'Ana Pereira',
      email: 'ana.pereira@example.com',
      avatar: 'AP',
      country: 'Portugal',
      flag: '🇵🇹',
      phone: '+351 912 345 678',
    },
    receiver: {
      name: 'Monir Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1211 234567',
    },
    amount: '€280.00',
    amountLocal: '৳33,320.00',
    fee: '€2.00',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€282.00',
    method: 'Nagad',
    methodType: 'wallet',
    purpose: 'Family Support',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '6:55 PM',
    timeAgo: '8 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '6:53 PM' },
      { label: 'Payment Confirmed', date: 'May 11, 2025', time: '6:54 PM' },
      { label: 'Completed', date: 'May 11, 2025', time: '6:55 PM' },
    ],
  },
  {
    id: 'TXN-2505124771',
    sender: {
      name: 'Marcus Brown',
      email: 'marcus.brown@example.com',
      avatar: 'MB',
      country: 'USA',
      flag: '🇺🇸',
      phone: '+1 212 555 0134',
    },
    receiver: {
      name: 'Shafiq Rahman',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1711 999888',
    },
    amount: '$750.00',
    amountLocal: '৳68,250.00',
    fee: '$4.00',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$754.00',
    method: 'Mastercard',
    methodType: 'card',
    purpose: 'Personal',
    status: 'Failed',
    date: 'May 11, 2025',
    time: '5:30 PM',
    timeAgo: '9 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '5:30 PM' },
      { label: 'Payment Failed', date: 'May 11, 2025', time: '5:31 PM' },
    ],
  },
  {
    id: 'TXN-2505124770',
    sender: {
      name: 'Yuki Tanaka',
      email: 'yuki.tanaka@example.com',
      avatar: 'YT',
      country: 'Japan',
      flag: '🇯🇵',
      phone: '+81 90 1234 5678',
    },
    receiver: {
      name: 'Bellal Uddin',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1811 888777',
    },
    amount: '¥65,000',
    amountLocal: '৳52,000.00',
    fee: '¥350',
    exchangeRate: '¥1 = ৳0.80',
    totalDebit: '¥65,350',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Education',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '4:10 PM',
    timeAgo: '10 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '4:08 PM' },
      { label: 'Payment Confirmed', date: 'May 11, 2025', time: '4:09 PM' },
      { label: 'Completed', date: 'May 11, 2025', time: '4:10 PM' },
    ],
  },
  // ── Page 3 ───────────────────────────────────────────────────────────────
  {
    id: 'TXN-2505124769',
    sender: {
      name: 'Elena Kovacs',
      email: 'elena.kovacs@example.com',
      avatar: 'EK',
      country: 'Hungary',
      flag: '🇭🇺',
      phone: '+36 30 123 4567',
    },
    receiver: {
      name: 'Hasan Ali',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1711 777666',
    },
    amount: '€320.00',
    amountLocal: '৳38,080.00',
    fee: '€2.50',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€322.50',
    method: 'Visa Card',
    methodType: 'card',
    purpose: 'Personal',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '3:45 PM',
    timeAgo: '11 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '3:43 PM' },
      { label: 'Completed', date: 'May 11, 2025', time: '3:45 PM' },
    ],
  },
  {
    id: 'TXN-2505124768',
    sender: {
      name: 'Carlos Mendez',
      email: 'carlos.m@example.com',
      avatar: 'CM',
      country: 'Spain',
      flag: '🇪🇸',
      phone: '+34 612 345 678',
    },
    receiver: {
      name: 'Sumaiya Islam',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1611 777666',
    },
    amount: '€500.00',
    amountLocal: '৳59,500.00',
    fee: '€3.50',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€503.50',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Business',
    status: 'Pending',
    date: 'May 11, 2025',
    time: '3:10 PM',
    timeAgo: '12 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '3:10 PM' },
    ],
  },
  {
    id: 'TXN-2505124767',
    sender: {
      name: 'Aisha Diallo',
      email: 'aisha.diallo@example.com',
      avatar: 'AD',
      country: 'France',
      flag: '🇫🇷',
      phone: '+33 7 12 34 56 78',
    },
    receiver: {
      name: 'Tariq Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1511 777666',
    },
    amount: '€175.00',
    amountLocal: '৳20,825.00',
    fee: '€1.50',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€176.50',
    method: 'bKash',
    methodType: 'wallet',
    purpose: 'Family Support',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '2:25 PM',
    timeAgo: '13 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '2:23 PM' },
      { label: 'Completed', date: 'May 11, 2025', time: '2:25 PM' },
    ],
  },
  {
    id: 'TXN-2505124766',
    sender: {
      name: 'Tom Bradley',
      email: 'tom.bradley@example.com',
      avatar: 'TB',
      country: 'USA',
      flag: '🇺🇸',
      phone: '+1 310 555 0145',
    },
    receiver: {
      name: 'Rezaul Karim',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1411 777666',
    },
    amount: '$1,200.00',
    amountLocal: '৳1,09,200.00',
    fee: '$6.00',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$1,206.00',
    method: 'Mastercard',
    methodType: 'card',
    purpose: 'Business',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '1:50 PM',
    timeAgo: '13 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '1:48 PM' },
      { label: 'Payment Confirmed', date: 'May 11, 2025', time: '1:49 PM' },
      { label: 'Completed', date: 'May 11, 2025', time: '1:50 PM' },
    ],
  },
  {
    id: 'TXN-2505124765',
    sender: {
      name: 'Hina Qureshi',
      email: 'hina.q@example.com',
      avatar: 'HQ',
      country: 'United Kingdom',
      flag: '🇬🇧',
      phone: '+44 7811 234567',
    },
    receiver: {
      name: 'Babul Akter',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1311 777666',
    },
    amount: '£380.00',
    amountLocal: '৳55,100.00',
    fee: '£2.80',
    exchangeRate: '1 GBP = ৳145.00',
    totalDebit: '£382.80',
    method: 'Nagad',
    methodType: 'wallet',
    purpose: 'Medical',
    status: 'Refunded',
    date: 'May 11, 2025',
    time: '12:30 PM',
    timeAgo: '14 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '12:28 PM' },
      { label: 'Payment Confirmed', date: 'May 11, 2025', time: '12:29 PM' },
      { label: 'Refunded', date: 'May 11, 2025', time: '12:30 PM' },
    ],
  },
  {
    id: 'TXN-2505124764',
    sender: {
      name: 'Pavel Novak',
      email: 'pavel.novak@example.com',
      avatar: 'PN',
      country: 'Czech Republic',
      flag: '🇨🇿',
      phone: '+420 601 234 567',
    },
    receiver: {
      name: 'Nasreen Akter',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1211 777666',
    },
    amount: '€230.00',
    amountLocal: '৳27,370.00',
    fee: '€2.00',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€232.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Personal',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '11:15 AM',
    timeAgo: '15 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '11:13 AM' },
      { label: 'Completed', date: 'May 11, 2025', time: '11:15 AM' },
    ],
  },
  {
    id: 'TXN-2505124763',
    sender: {
      name: 'Mei Chen',
      email: 'mei.chen@example.com',
      avatar: 'MC',
      country: 'Singapore',
      flag: '🇸🇬',
      phone: '+65 9123 4567',
    },
    receiver: {
      name: 'Sabbir Khan',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1711 666555',
    },
    amount: 'SGD 550.00',
    amountLocal: '৳44,550.00',
    fee: 'SGD 3.50',
    exchangeRate: '1 SGD = ৳81.00',
    totalDebit: 'SGD 553.50',
    method: 'Mobile Wallet',
    methodType: 'wallet',
    purpose: 'Education',
    status: 'Pending',
    date: 'May 11, 2025',
    time: '10:30 AM',
    timeAgo: '16 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '10:30 AM' },
    ],
  },
  {
    id: 'TXN-2505124762',
    sender: {
      name: 'Ali Hassan',
      email: 'ali.hassan@example.com',
      avatar: 'AH2',
      country: 'UAE',
      flag: '🇦🇪',
      phone: '+971 52 345 6789',
    },
    receiver: {
      name: 'Roksana Begum',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1811 666555',
    },
    amount: 'AED 800.00',
    amountLocal: '৳24,000.00',
    fee: 'AED 4.00',
    exchangeRate: '1 AED = ৳30.00',
    totalDebit: 'AED 804.00',
    method: 'Cash Pickup',
    methodType: 'cash',
    purpose: 'Family Support',
    status: 'Failed',
    date: 'May 11, 2025',
    time: '9:45 AM',
    timeAgo: '17 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '9:45 AM' },
      { label: 'Payment Failed', date: 'May 11, 2025', time: '9:46 AM' },
    ],
  },
  {
    id: 'TXN-2505124761',
    sender: {
      name: 'Lena Fischer',
      email: 'lena.f@example.com',
      avatar: 'LF',
      country: 'Germany',
      flag: '🇩🇪',
      phone: '+49 160 987 6543',
    },
    receiver: {
      name: 'Tarek Miah',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1911 666555',
    },
    amount: '€410.00',
    amountLocal: '৳48,790.00',
    fee: '€3.00',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€413.00',
    method: 'Visa Card',
    methodType: 'card',
    purpose: 'Business',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '8:50 AM',
    timeAgo: '18 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '8:48 AM' },
      { label: 'Completed', date: 'May 11, 2025', time: '8:50 AM' },
    ],
  },
  {
    id: 'TXN-2505124760',
    sender: {
      name: 'Hamid Sultani',
      email: 'hamid.s@example.com',
      avatar: 'HS',
      country: 'Afghanistan',
      flag: '🇦🇫',
      phone: '+93 70 123 4567',
    },
    receiver: {
      name: 'Masum Billah',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1611 666555',
    },
    amount: '$350.00',
    amountLocal: '৳31,850.00',
    fee: '$2.50',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$352.50',
    method: 'bKash',
    methodType: 'wallet',
    purpose: 'Personal',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '7:20 AM',
    timeAgo: '19 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '7:18 AM' },
      { label: 'Completed', date: 'May 11, 2025', time: '7:20 AM' },
    ],
  },
  // ── Page 4 ───────────────────────────────────────────────────────────────
  {
    id: 'TXN-2505124759',
    sender: {
      name: 'Robert Kim',
      email: 'robert.kim@example.com',
      avatar: 'RK',
      country: 'South Korea',
      flag: '🇰🇷',
      phone: '+82 10 1234 5678',
    },
    receiver: {
      name: 'Arifa Khatun',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1511 555444',
    },
    amount: 'KRW 680,000',
    amountLocal: '৳54,400.00',
    fee: 'KRW 3,500',
    exchangeRate: 'KRW 1,000 = ৳80.00',
    totalDebit: 'KRW 683,500',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Education',
    status: 'Completed',
    date: 'May 11, 2025',
    time: '6:00 AM',
    timeAgo: '20 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 11, 2025', time: '5:58 AM' },
      { label: 'Completed', date: 'May 11, 2025', time: '6:00 AM' },
    ],
  },
  {
    id: 'TXN-2505124758',
    sender: {
      name: 'Olivia Grant',
      email: 'olivia.g@example.com',
      avatar: 'OG',
      country: 'Canada',
      flag: '🇨🇦',
      phone: '+1 604 555 0167',
    },
    receiver: {
      name: 'Mamun Rashid',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1411 555444',
    },
    amount: 'CAD 600.00',
    amountLocal: '৳48,000.00',
    fee: 'CAD 4.00',
    exchangeRate: '1 CAD = ৳80.00',
    totalDebit: 'CAD 604.00',
    method: 'Mastercard',
    methodType: 'card',
    purpose: 'Family Support',
    status: 'Pending',
    date: 'May 10, 2025',
    time: '11:30 PM',
    timeAgo: '21 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '11:30 PM' },
    ],
  },
  {
    id: 'TXN-2505124757',
    sender: {
      name: 'Ibrahim Al-Rashid',
      email: 'ibrahim.ar@example.com',
      avatar: 'IR',
      country: 'Qatar',
      flag: '🇶🇦',
      phone: '+974 5012 3456',
    },
    receiver: {
      name: 'Limon Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1311 555444',
    },
    amount: 'QAR 1,800.00',
    amountLocal: '৳54,000.00',
    fee: 'QAR 9.00',
    exchangeRate: '1 QAR = ৳30.00',
    totalDebit: 'QAR 1,809.00',
    method: 'Cash Pickup',
    methodType: 'cash',
    purpose: 'Medical',
    status: 'Completed',
    date: 'May 10, 2025',
    time: '10:15 PM',
    timeAgo: '22 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '10:13 PM' },
      { label: 'Completed', date: 'May 10, 2025', time: '10:15 PM' },
    ],
  },
  {
    id: 'TXN-2505124756',
    sender: {
      name: 'Mina Johansson',
      email: 'mina.j@example.com',
      avatar: 'MJ',
      country: 'Sweden',
      flag: '🇸🇪',
      phone: '+46 70 123 4567',
    },
    receiver: {
      name: 'Kohinoor Begum',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1211 555444',
    },
    amount: 'SEK 3,200.00',
    amountLocal: '৳35,200.00',
    fee: 'SEK 18.00',
    exchangeRate: 'SEK 1 = ৳11.00',
    totalDebit: 'SEK 3,218.00',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Personal',
    status: 'Refunded',
    date: 'May 10, 2025',
    time: '9:00 PM',
    timeAgo: '23 hours ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '8:58 PM' },
      { label: 'Refunded', date: 'May 10, 2025', time: '9:00 PM' },
    ],
  },
  {
    id: 'TXN-2505124755',
    sender: {
      name: 'Chidi Okonkwo',
      email: 'chidi.o@example.com',
      avatar: 'CO',
      country: 'Nigeria',
      flag: '🇳🇬',
      phone: '+234 803 123 4567',
    },
    receiver: {
      name: 'Zahir Uddin',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1711 444333',
    },
    amount: '$480.00',
    amountLocal: '৳43,680.00',
    fee: '$3.20',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$483.20',
    method: 'Mobile Wallet',
    methodType: 'wallet',
    purpose: 'Business',
    status: 'Completed',
    date: 'May 10, 2025',
    time: '8:10 PM',
    timeAgo: '1 day ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '8:08 PM' },
      { label: 'Completed', date: 'May 10, 2025', time: '8:10 PM' },
    ],
  },
  {
    id: 'TXN-2505124754',
    sender: {
      name: 'Sara Lindqvist',
      email: 'sara.l@example.com',
      avatar: 'SL',
      country: 'Norway',
      flag: '🇳🇴',
      phone: '+47 912 34 567',
    },
    receiver: {
      name: 'Shakila Akter',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1811 444333',
    },
    amount: 'NOK 3,000.00',
    amountLocal: '৳33,000.00',
    fee: 'NOK 16.00',
    exchangeRate: 'NOK 1 = ৳11.00',
    totalDebit: 'NOK 3,016.00',
    method: 'Visa Card',
    methodType: 'card',
    purpose: 'Family Support',
    status: 'Failed',
    date: 'May 10, 2025',
    time: '7:00 PM',
    timeAgo: '1 day ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '7:00 PM' },
      { label: 'Payment Failed', date: 'May 10, 2025', time: '7:01 PM' },
    ],
  },
  {
    id: 'TXN-2505124753',
    sender: {
      name: 'Reza Tehrani',
      email: 'reza.t@example.com',
      avatar: 'RT',
      country: 'Iran',
      flag: '🇮🇷',
      phone: '+98 912 345 6789',
    },
    receiver: {
      name: 'Dulal Hossain',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1911 444333',
    },
    amount: '$220.00',
    amountLocal: '৳20,020.00',
    fee: '$2.00',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$222.00',
    method: 'Nagad',
    methodType: 'wallet',
    purpose: 'Education',
    status: 'Completed',
    date: 'May 10, 2025',
    time: '5:45 PM',
    timeAgo: '1 day ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '5:43 PM' },
      { label: 'Completed', date: 'May 10, 2025', time: '5:45 PM' },
    ],
  },
  {
    id: 'TXN-2505124752',
    sender: {
      name: 'Grace Osei',
      email: 'grace.osei@example.com',
      avatar: 'GO',
      country: 'Ghana',
      flag: '🇬🇭',
      phone: '+233 24 123 4567',
    },
    receiver: {
      name: 'Alim Uddin',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1611 444333',
    },
    amount: '$310.00',
    amountLocal: '৳28,210.00',
    fee: '$2.50',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$312.50',
    method: 'Bank Transfer',
    methodType: 'bank',
    purpose: 'Medical',
    status: 'Pending',
    date: 'May 10, 2025',
    time: '4:20 PM',
    timeAgo: '1 day ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '4:20 PM' },
    ],
  },
  {
    id: 'TXN-2505124751',
    sender: {
      name: 'Tomás García',
      email: 'tomas.g@example.com',
      avatar: 'TG',
      country: 'Mexico',
      flag: '🇲🇽',
      phone: '+52 55 1234 5678',
    },
    receiver: {
      name: 'Nasim Uddin',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1511 444333',
    },
    amount: '$560.00',
    amountLocal: '৳50,960.00',
    fee: '$3.50',
    exchangeRate: '1 USD = ৳91.00',
    totalDebit: '$563.50',
    method: 'Cash Pickup',
    methodType: 'cash',
    purpose: 'Personal',
    status: 'Completed',
    date: 'May 10, 2025',
    time: '3:00 PM',
    timeAgo: '1 day ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '2:58 PM' },
      { label: 'Completed', date: 'May 10, 2025', time: '3:00 PM' },
    ],
  },
  {
    id: 'TXN-2505124750',
    sender: {
      name: 'Amara Diarra',
      email: 'amara.d@example.com',
      avatar: 'AM',
      country: 'Senegal',
      flag: '🇸🇳',
      phone: '+221 77 123 4567',
    },
    receiver: {
      name: 'Rahela Begum',
      country: 'Bangladesh',
      flag: '🇧🇩',
      phone: '+880 1411 444333',
    },
    amount: '€190.00',
    amountLocal: '৳22,610.00',
    fee: '€1.80',
    exchangeRate: '1 EUR = ৳119.00',
    totalDebit: '€191.80',
    method: 'bKash',
    methodType: 'wallet',
    purpose: 'Family Support',
    status: 'Completed',
    date: 'May 10, 2025',
    time: '1:30 PM',
    timeAgo: '1 day ago',
    timeline: [
      { label: 'Transaction Created', date: 'May 10, 2025', time: '1:28 PM' },
      { label: 'Completed', date: 'May 10, 2025', time: '1:30 PM' },
    ],
  },
];

export const txStatusOptions = [
  'All Status',
  'Completed',
  'Pending',
  'Failed',
  'Refunded',
];

export const txCountryOptions = [
  'All Countries',
  'United Kingdom',
  'UAE',
  'Saudi Arabia',
  'Malaysia',
  'Germany',
  'Australia',
  'Italy',
  'France',
  'Canada',
  'USA',
  'Japan',
  'Singapore',
  'Qatar',
  'South Korea',
  'Norway',
  'Sweden',
  'Nigeria',
  'Ghana',
  'Portugal',
  'Spain',
  'Hungary',
  'Czech Republic',
  'Mexico',
  'Senegal',
  'Afghanistan',
  'Iran',
];

export const txMethodOptions = [
  'All Methods',
  'Visa Card',
  'Mastercard',
  'Bank Transfer',
  'Cash Pickup',
  'Mobile Wallet',
  'bKash',
  'Nagad',
];

export const TX_TOTAL = 2475;
export const TX_PAGE_SIZE = 10;


// Beneficials fake data here

export type BeneficiaryStatus = 'Active' | 'Inactive' | 'Pending';

export interface Beneficiary {
  id: string;
  name: string;
  email: string;
  phone: string;
  avatar: string;
  country: string;
  countryFlag: string;
  bankName: string;
  bankBranch: string;
  accountNumber: string;
  routingNumber: string;
  swiftCode: string;
  accountType: 'Savings Account' | 'Current Account' | 'Checking Account';
  iban?: string;
  currency: string;
  currencyName: string;
  status: BeneficiaryStatus;
  addedOn: string;
  addedTime: string;
  dateOfBirth: string;
  address: string;
  preferredCurrency: string;
  purpose: string;
  relationship: string;
  lastTransaction: string;
  totalTransactions: number;
  totalReceived: string;
}

export const beneficiariesData: Beneficiary[] = [
  {
    id: 'BEN-001',
    name: 'Rahim Uddin',
    email: 'rahim.uddin@example.com',
    phone: '+880 1712 345678',
    avatar: 'RU',
    country: 'Bangladesh',
    countryFlag: '🇧🇩',
    bankName: 'Eastern Bank Ltd.',
    bankBranch: 'Dhanmondi Branch',
    accountNumber: '1234 5678 9012',
    routingNumber: '055263',
    swiftCode: 'EBLDBDDH',
    accountType: 'Savings Account',
    currency: 'BDT',
    currencyName: 'Bangladeshi Taka',
    status: 'Active',
    addedOn: 'May 12, 2025',
    addedTime: '2:30 PM',
    dateOfBirth: 'May 20, 1990',
    address: 'House 12, Road 5, Dhanmondi, Dhaka 1205, Bangladesh',
    preferredCurrency: 'BDT - Bangladeshi Taka',
    purpose: 'Family Support',
    relationship: 'Family',
    lastTransaction: 'May 12, 2025',
    totalTransactions: 12,
    totalReceived: '৳125,450.00',
  },
  {
    id: 'BEN-002',
    name: 'Maria Santos',
    email: 'maria.santos@example.com',
    phone: '+63 917 123 4567',
    avatar: 'MS',
    country: 'Philippines',
    countryFlag: '🇵🇭',
    bankName: 'BDO Unibank, Inc.',
    bankBranch: 'Makati Branch',
    accountNumber: '0012 3456 7890',
    routingNumber: 'BNORPHMM',
    swiftCode: 'BNORPHMM',
    accountType: 'Savings Account',
    currency: 'PHP',
    currencyName: 'Philippine Peso',
    status: 'Active',
    addedOn: 'May 12, 2025',
    addedTime: '10:15 AM',
    dateOfBirth: 'March 14, 1988',
    address: '45 Ayala Avenue, Makati City, Metro Manila, Philippines',
    preferredCurrency: 'PHP - Philippine Peso',
    purpose: 'Family Support',
    relationship: 'Friend',
    lastTransaction: 'May 11, 2025',
    totalTransactions: 8,
    totalReceived: '₱98,200.00',
  },
  {
    id: 'BEN-003',
    name: 'Arif Khan',
    email: 'arif.khan@example.com',
    phone: '+92 301 2345678',
    avatar: 'AK',
    country: 'Pakistan',
    countryFlag: '🇵🇰',
    bankName: 'Meezan Bank',
    bankBranch: 'Karachi Branch',
    accountNumber: 'PK12 MEZN 0001',
    routingNumber: '2345 6789 01',
    swiftCode: 'MEZNPKKA',
    accountType: 'Current Account',
    iban: 'PK12MEZN0001234567890',
    currency: 'PKR',
    currencyName: 'Pakistani Rupee',
    status: 'Active',
    addedOn: 'May 11, 2025',
    addedTime: '6:45 PM',
    dateOfBirth: 'July 8, 1992',
    address: 'Plot 22, Block B, Gulshan-e-Iqbal, Karachi, Pakistan',
    preferredCurrency: 'PKR - Pakistani Rupee',
    purpose: 'Business',
    relationship: 'Business Partner',
    lastTransaction: 'May 10, 2025',
    totalTransactions: 5,
    totalReceived: '₨145,000.00',
  },
  {
    id: 'BEN-004',
    name: 'Mohammad Ali',
    email: 'mohammad.ali@example.com',
    phone: '+971 60 123 4567',
    avatar: 'MA',
    country: 'UAE',
    countryFlag: '🇦🇪',
    bankName: 'Emirates NBD',
    bankBranch: 'Dubai Branch',
    accountNumber: 'AE07 0260 0012',
    routingNumber: '3456 7890 001',
    swiftCode: 'EBILAEAD',
    accountType: 'Current Account',
    iban: 'AE070260001234567890123',
    currency: 'AED',
    currencyName: 'UAE Dirham',
    status: 'Active',
    addedOn: 'May 11, 2025',
    addedTime: '3:20 PM',
    dateOfBirth: 'January 25, 1985',
    address: 'Villa 7, Al Barsha 1, Dubai, United Arab Emirates',
    preferredCurrency: 'AED - UAE Dirham',
    purpose: 'Business',
    relationship: 'Business Partner',
    lastTransaction: 'May 9, 2025',
    totalTransactions: 15,
    totalReceived: 'AED 85,200.00',
  },
  {
    id: 'BEN-005',
    name: 'Ibrahim Khalil',
    email: 'ibrahim.khalil@example.com',
    phone: '+966 55 123 4567',
    avatar: 'IK',
    country: 'Saudi Arabia',
    countryFlag: '🇸🇦',
    bankName: 'Al Rajhi Bank',
    bankBranch: 'Riyadh Branch',
    accountNumber: 'SA12 8000 0123',
    routingNumber: '4567 8901 2345',
    swiftCode: 'RJHISARI',
    accountType: 'Savings Account',
    iban: 'SA128000012345678901234',
    currency: 'SAR',
    currencyName: 'Saudi Riyal',
    status: 'Inactive',
    addedOn: 'May 10, 2025',
    addedTime: '11:05 AM',
    dateOfBirth: 'April 3, 1978',
    address: 'Street 15, Al Olaya District, Riyadh 12214, Saudi Arabia',
    preferredCurrency: 'SAR - Saudi Riyal',
    purpose: 'Family Support',
    relationship: 'Relative',
    lastTransaction: 'April 28, 2025',
    totalTransactions: 3,
    totalReceived: 'SAR 12,500.00',
  },
  {
    id: 'BEN-006',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '+91 98765 43210',
    avatar: 'PS',
    country: 'India',
    countryFlag: '🇮🇳',
    bankName: 'HDFC Bank',
    bankBranch: 'Mumbai Branch',
    accountNumber: '5010 1234 5678',
    routingNumber: 'IFSC: HDFC0001234',
    swiftCode: 'HDFCINBB',
    accountType: 'Savings Account',
    currency: 'INR',
    currencyName: 'Indian Rupee',
    status: 'Active',
    addedOn: 'May 10, 2025',
    addedTime: '9:30 AM',
    dateOfBirth: 'September 12, 1993',
    address: 'Flat 301, Sunflower Apt, Bandra West, Mumbai 400050, India',
    preferredCurrency: 'INR - Indian Rupee',
    purpose: 'Education',
    relationship: 'Friend',
    lastTransaction: 'May 10, 2025',
    totalTransactions: 7,
    totalReceived: '₹62,300.00',
  },
  {
    id: 'BEN-007',
    name: 'Samuel Okafor',
    email: 'samuel.okafor@example.com',
    phone: '+234 803 123 4567',
    avatar: 'SO',
    country: 'Nigeria',
    countryFlag: '🇳🇬',
    bankName: 'GTBank',
    bankBranch: 'Lagos Branch',
    accountNumber: '0123456789',
    routingNumber: 'Sort Code: 058152',
    swiftCode: 'GTBINGLA',
    accountType: 'Current Account',
    currency: 'NGN',
    currencyName: 'Nigerian Naira',
    status: 'Pending',
    addedOn: 'May 9, 2025',
    addedTime: '5:10 PM',
    dateOfBirth: 'February 19, 1991',
    address: '12 Admiralty Way, Lekki Phase 1, Lagos, Nigeria',
    preferredCurrency: 'NGN - Nigerian Naira',
    purpose: 'Business',
    relationship: 'Business Partner',
    lastTransaction: 'May 8, 2025',
    totalTransactions: 2,
    totalReceived: '₦85,000.00',
  },
  {
    id: 'BEN-008',
    name: 'Siti Aisyah',
    email: 'siti.aisyah@example.com',
    phone: '+60 12 345 6789',
    avatar: 'SA',
    country: 'Malaysia',
    countryFlag: '🇲🇾',
    bankName: 'Maybank',
    bankBranch: 'Kuala Lumpur Branch',
    accountNumber: '5143 1234 5678',
    routingNumber: 'SWIFT: MBEMYKL',
    swiftCode: 'MBEMYKL',
    accountType: 'Savings Account',
    currency: 'MYR',
    currencyName: 'Malaysian Ringgit',
    status: 'Active',
    addedOn: 'May 9, 2025',
    addedTime: '2:45 PM',
    dateOfBirth: 'June 30, 1995',
    address: 'No. 8, Jalan Ampang, Kuala Lumpur 50450, Malaysia',
    preferredCurrency: 'MYR - Malaysian Ringgit',
    purpose: 'Family Support',
    relationship: 'Family',
    lastTransaction: 'May 9, 2025',
    totalTransactions: 9,
    totalReceived: 'MYR 18,900.00',
  },
  {
    id: 'BEN-009',
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    phone: '+44 7700 900129',
    avatar: 'DW',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    bankName: 'Barclays Bank',
    bankBranch: 'London Branch',
    accountNumber: 'GB29 BARC 2013',
    routingNumber: '1234 56 90',
    swiftCode: 'BARCGB22',
    accountType: 'Current Account',
    iban: 'GB29BARCXXXXXXXX',
    currency: 'GBP',
    currencyName: 'British Pound',
    status: 'Active',
    addedOn: 'May 8, 2025',
    addedTime: '11:00 AM',
    dateOfBirth: 'November 5, 1982',
    address: '14 Baker Street, Marylebone, London W1U 3BW, United Kingdom',
    preferredCurrency: 'GBP - British Pound',
    purpose: 'Business',
    relationship: 'Business Partner',
    lastTransaction: 'May 7, 2025',
    totalTransactions: 20,
    totalReceived: '£42,800.00',
  },
  {
    id: 'BEN-010',
    name: 'Emily Johnson',
    email: 'emily.johnson@example.com',
    phone: '+1 202 555 0198',
    avatar: 'EJ',
    country: 'United States',
    countryFlag: '🇺🇸',
    bankName: 'Chase Bank',
    bankBranch: 'New York Branch',
    accountNumber: '1234 5678 9012',
    routingNumber: 'Routing: 021000021',
    swiftCode: 'CHASUS33',
    accountType: 'Checking Account',
    currency: 'USD',
    currencyName: 'US Dollar',
    status: 'Active',
    addedOn: 'May 8, 2025',
    addedTime: '9:15 AM',
    dateOfBirth: 'August 17, 1990',
    address: '250 West 57th Street, New York, NY 10107, USA',
    preferredCurrency: 'USD - US Dollar',
    purpose: 'Personal',
    relationship: 'Friend',
    lastTransaction: 'May 6, 2025',
    totalTransactions: 4,
    totalReceived: '$8,200.00',
  },
  {
    id: 'BEN-011',
    name: 'Karim Hassan',
    email: 'karim.hassan@example.com',
    phone: '+49 170 123 4567',
    avatar: 'KH',
    country: 'Germany',
    countryFlag: '🇩🇪',
    bankName: 'Deutsche Bank',
    bankBranch: 'Berlin Branch',
    accountNumber: 'DE89 3704 0044',
    routingNumber: '3704 0044 0532',
    swiftCode: 'DEUTDEDB',
    accountType: 'Current Account',
    iban: 'DE89370400440532013000',
    currency: 'EUR',
    currencyName: 'Euro',
    status: 'Active',
    addedOn: 'May 7, 2025',
    addedTime: '4:00 PM',
    dateOfBirth: 'December 22, 1987',
    address: 'Friedrichstraße 45, 10117 Berlin, Germany',
    preferredCurrency: 'EUR - Euro',
    purpose: 'Education',
    relationship: 'Friend',
    lastTransaction: 'May 5, 2025',
    totalTransactions: 6,
    totalReceived: '€14,500.00',
  },
  {
    id: 'BEN-012',
    name: 'Nadia Islam',
    email: 'nadia.islam@example.com',
    phone: '+61 412 345 678',
    avatar: 'NI',
    country: 'Australia',
    countryFlag: '🇦🇺',
    bankName: 'Commonwealth Bank',
    bankBranch: 'Sydney Branch',
    accountNumber: '0625 7654 3210',
    routingNumber: 'BSB: 062500',
    swiftCode: 'CTBAAU2S',
    accountType: 'Savings Account',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
    status: 'Active',
    addedOn: 'May 7, 2025',
    addedTime: '1:30 PM',
    dateOfBirth: 'March 8, 1994',
    address: '88 George Street, Sydney NSW 2000, Australia',
    preferredCurrency: 'AUD - Australian Dollar',
    purpose: 'Family Support',
    relationship: 'Family',
    lastTransaction: 'May 6, 2025',
    totalTransactions: 11,
    totalReceived: 'AUD 22,100.00',
  },
  {
    id: 'BEN-013',
    name: 'Omar Sheikh',
    email: 'omar.sheikh@example.com',
    phone: '+974 5012 3456',
    avatar: 'OS',
    country: 'Qatar',
    countryFlag: '🇶🇦',
    bankName: 'Qatar National Bank',
    bankBranch: 'Doha Branch',
    accountNumber: 'QA58 QNBA 0000',
    routingNumber: '0000 6935 0063',
    swiftCode: 'QNBAQAQA',
    accountType: 'Savings Account',
    iban: 'QA58QNBA0000000069350063',
    currency: 'QAR',
    currencyName: 'Qatari Riyal',
    status: 'Active',
    addedOn: 'May 6, 2025',
    addedTime: '8:20 AM',
    dateOfBirth: 'May 11, 1980',
    address: 'Villa 45, West Bay, Doha, Qatar',
    preferredCurrency: 'QAR - Qatari Riyal',
    purpose: 'Business',
    relationship: 'Business Partner',
    lastTransaction: 'May 4, 2025',
    totalTransactions: 18,
    totalReceived: 'QAR 95,000.00',
  },
  {
    id: 'BEN-014',
    name: 'Fatima Malik',
    email: 'fatima.malik@example.com',
    phone: '+1 416 555 0123',
    avatar: 'FM',
    country: 'Canada',
    countryFlag: '🇨🇦',
    bankName: 'Royal Bank of Canada',
    bankBranch: 'Toronto Branch',
    accountNumber: '1234 567 890',
    routingNumber: '003 00012',
    swiftCode: 'ROYCCAT2',
    accountType: 'Checking Account',
    currency: 'CAD',
    currencyName: 'Canadian Dollar',
    status: 'Active',
    addedOn: 'May 6, 2025',
    addedTime: '3:45 PM',
    dateOfBirth: 'October 29, 1989',
    address: '120 Queen Street West, Toronto, ON M5H 2M9, Canada',
    preferredCurrency: 'CAD - Canadian Dollar',
    purpose: 'Education',
    relationship: 'Friend',
    lastTransaction: 'May 3, 2025',
    totalTransactions: 9,
    totalReceived: 'CAD 32,400.00',
  },
  {
    id: 'BEN-015',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@example.com',
    phone: '+81 90 1234 5678',
    avatar: 'YT',
    country: 'Japan',
    countryFlag: '🇯🇵',
    bankName: 'Sumitomo Mitsui Bank',
    bankBranch: 'Tokyo Branch',
    accountNumber: '1234567',
    routingNumber: 'Branch: 001',
    swiftCode: 'SMBCJPJT',
    accountType: 'Savings Account',
    currency: 'JPY',
    currencyName: 'Japanese Yen',
    status: 'Inactive',
    addedOn: 'May 5, 2025',
    addedTime: '10:00 AM',
    dateOfBirth: 'July 7, 1996',
    address: '2-1-1 Marunouchi, Chiyoda-ku, Tokyo 100-0005, Japan',
    preferredCurrency: 'JPY - Japanese Yen',
    purpose: 'Personal',
    relationship: 'Friend',
    lastTransaction: 'April 20, 2025',
    totalTransactions: 3,
    totalReceived: '¥245,000',
  },
  {
    id: 'BEN-016',
    name: 'Ana Pereira',
    email: 'ana.pereira@example.com',
    phone: '+351 912 345 678',
    avatar: 'AP',
    country: 'Portugal',
    countryFlag: '🇵🇹',
    bankName: 'Caixa Geral de Depósitos',
    bankBranch: 'Lisbon Branch',
    accountNumber: 'PT50 0035 0292',
    routingNumber: '0000 0001 7388',
    swiftCode: 'CGDIPTPL',
    accountType: 'Savings Account',
    iban: 'PT50003502920000000173886',
    currency: 'EUR',
    currencyName: 'Euro',
    status: 'Active',
    addedOn: 'May 5, 2025',
    addedTime: '2:00 PM',
    dateOfBirth: 'February 14, 1991',
    address: 'Rua Augusta 100, 1100-053 Lisboa, Portugal',
    preferredCurrency: 'EUR - Euro',
    purpose: 'Family Support',
    relationship: 'Family',
    lastTransaction: 'May 2, 2025',
    totalTransactions: 7,
    totalReceived: '€18,750.00',
  },
  {
    id: 'BEN-017',
    name: 'Chidi Okonkwo',
    email: 'chidi.okonkwo@example.com',
    phone: '+234 805 678 9012',
    avatar: 'CO',
    country: 'Nigeria',
    countryFlag: '🇳🇬',
    bankName: 'Access Bank',
    bankBranch: 'Abuja Branch',
    accountNumber: '0987654321',
    routingNumber: 'Sort Code: 044150',
    swiftCode: 'ABNGNGLA',
    accountType: 'Current Account',
    currency: 'NGN',
    currencyName: 'Nigerian Naira',
    status: 'Active',
    addedOn: 'May 4, 2025',
    addedTime: '7:30 PM',
    dateOfBirth: 'August 20, 1986',
    address: 'Plot 1234, Wuse Zone 4, Abuja FCT, Nigeria',
    preferredCurrency: 'NGN - Nigerian Naira',
    purpose: 'Business',
    relationship: 'Business Partner',
    lastTransaction: 'May 1, 2025',
    totalTransactions: 14,
    totalReceived: '₦420,000.00',
  },
  {
    id: 'BEN-018',
    name: 'Mei Chen',
    email: 'mei.chen@example.com',
    phone: '+65 9123 4567',
    avatar: 'MC',
    country: 'Singapore',
    countryFlag: '🇸🇬',
    bankName: 'DBS Bank',
    bankBranch: 'Orchard Branch',
    accountNumber: '1234 5678 901',
    routingNumber: 'Bank Code: 7171',
    swiftCode: 'DBSSSGSG',
    accountType: 'Savings Account',
    currency: 'SGD',
    currencyName: 'Singapore Dollar',
    status: 'Active',
    addedOn: 'May 4, 2025',
    addedTime: '11:15 AM',
    dateOfBirth: 'April 5, 1993',
    address: '80 Robinson Road, #02-00, Singapore 068898',
    preferredCurrency: 'SGD - Singapore Dollar',
    purpose: 'Education',
    relationship: 'Friend',
    lastTransaction: 'April 30, 2025',
    totalTransactions: 5,
    totalReceived: 'SGD 12,300.00',
  },
  {
    id: 'BEN-019',
    name: 'Marcus Brown',
    email: 'marcus.brown@example.com',
    phone: '+1 212 555 0134',
    avatar: 'MB',
    country: 'United States',
    countryFlag: '🇺🇸',
    bankName: 'Bank of America',
    bankBranch: 'Manhattan Branch',
    accountNumber: '9876 5432 1098',
    routingNumber: 'Routing: 026009593',
    swiftCode: 'BOFAUS3N',
    accountType: 'Checking Account',
    currency: 'USD',
    currencyName: 'US Dollar',
    status: 'Active',
    addedOn: 'May 3, 2025',
    addedTime: '4:50 PM',
    dateOfBirth: 'January 30, 1984',
    address: '1 Bryant Park, New York, NY 10036, USA',
    preferredCurrency: 'USD - US Dollar',
    purpose: 'Personal',
    relationship: 'Friend',
    lastTransaction: 'April 28, 2025',
    totalTransactions: 6,
    totalReceived: '$15,600.00',
  },
  {
    id: 'BEN-020',
    name: 'Lena Fischer',
    email: 'lena.fischer@example.com',
    phone: '+49 160 987 6543',
    avatar: 'LF',
    country: 'Germany',
    countryFlag: '🇩🇪',
    bankName: 'Commerzbank',
    bankBranch: 'Frankfurt Branch',
    accountNumber: 'DE75 2004 0060',
    routingNumber: '6274 3015 06',
    swiftCode: 'COBADEFF',
    accountType: 'Current Account',
    iban: 'DE75200400600627430150 6',
    currency: 'EUR',
    currencyName: 'Euro',
    status: 'Inactive',
    addedOn: 'May 2, 2025',
    addedTime: '9:00 AM',
    dateOfBirth: 'June 18, 1990',
    address: 'Kaiserstraße 29, 60311 Frankfurt am Main, Germany',
    preferredCurrency: 'EUR - Euro',
    purpose: 'Medical',
    relationship: 'Relative',
    lastTransaction: 'April 15, 2025',
    totalTransactions: 4,
    totalReceived: '€9,800.00',
  },
];

export const beneficiaryCountryOptions = [
  'All Countries',
  'Bangladesh',
  'Philippines',
  'Pakistan',
  'UAE',
  'Saudi Arabia',
  'India',
  'Nigeria',
  'Malaysia',
  'United Kingdom',
  'United States',
  'Germany',
  'Australia',
  'Qatar',
  'Canada',
  'Japan',
  'Portugal',
  'Singapore',
];

export const beneficiaryStatusOptions = ['All Status', 'Active', 'Inactive', 'Pending'];

export const beneficiaryCurrencyOptions = [
  'All Currencies',
  'BDT - Bangladeshi Taka',
  'PHP - Philippine Peso',
  'PKR - Pakistani Rupee',
  'AED - UAE Dirham',
  'SAR - Saudi Riyal',
  'INR - Indian Rupee',
  'NGN - Nigerian Naira',
  'MYR - Malaysian Ringgit',
  'GBP - British Pound',
  'USD - US Dollar',
  'EUR - Euro',
  'AUD - Australian Dollar',
  'QAR - Qatari Riyal',
  'CAD - Canadian Dollar',
  'JPY - Japanese Yen',
  'SGD - Singapore Dollar',
];

export const BENEFICIARY_TOTAL = 2458;
export const BENEFICIARY_ACTIVE = 2156;
export const BENEFICIARY_INACTIVE = 186;
export const BENEFICIARY_WEEK_ADDED = 45;
export const BENEFICIARY_PAGE_SIZE = 10;

// report & analytics fake data here


// ── Reports & Analytics Fake Data ─────────────────────────────────────────────

// Stat cards
export const reportStatCards = [
  { label: 'Total Transactions', value: '24,752', change: '+12.5%', positive: true, sub: 'vs last 7 days', color: 'blue' },
  { label: 'Total Cash Pickups', value: '8,642', change: '+8.3%', positive: true, sub: 'vs last 7 days', color: 'orange' },
  { label: 'Total Revenue (Fees)', value: '$425,780', change: '+15.7%', positive: true, sub: 'vs last 7 days', color: 'green' },
  { label: 'Total Payouts', value: '$4,256,540', change: '+10.2%', positive: true, sub: 'vs last 7 days', color: 'teal' },
  { label: 'Pending Transactions', value: '1,248', change: '+5.2%', positive: true, sub: 'vs last 7 days', color: 'yellow' },
  { label: 'Failed Transactions', value: '156', change: '-3.1%', positive: false, sub: 'vs last 7 days', color: 'red' },
  { label: 'Active Users', value: '12,856', change: '+9.4%', positive: true, sub: 'vs last 7 days', color: 'purple' },
  { label: 'Active Agents', value: '214', change: '+6.7%', positive: true, sub: 'vs last 7 days', color: 'pink' },
];

// Daily Transaction Volume (May 6–12)
export const dailyVolumeData = {
  labels: ['May 6', 'May 7', 'May 8', 'May 9', 'May 10', 'May 11', 'May 12'],
  values: [2100, 3200, 2800, 3800, 3400, 4600, 4900],
};

// Monthly Revenue Trend (Nov–May)
export const monthlyRevenueData = {
  labels: ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May'],
  revenue: [180000, 220000, 160000, 290000, 340000, 410000, 425780],
  fees: [12000, 15000, 11000, 19000, 23000, 28000, 30000],
};

// Status Distribution (donut)
export const statusDistribution = [
  { label: 'Completed', value: 18752, pct: 75.8, color: '#16a34a' },
  { label: 'Pending', value: 3124, pct: 12.6, color: '#f59e0b' },
  { label: 'Failed', value: 1563, pct: 6.3, color: '#ef4444' },
  { label: 'Refunded', value: 1313, pct: 5.3, color: '#6366f1' },
];

// Recent Transactions (analytics view)
export interface AnalyticsTransaction {
  id: string;
  sender: string;
  recipient: string;
  sendCountry: string;
  sendFlag: string;
  receiveCountry: string;
  receiveFlag: string;
  amount: string;
  currency: string;
  rate: string;
  fee: string;
  netPayout: string;
  status: 'Completed' | 'Pending' | 'Failed';
  dateTime: string;
}

export const analyticsRecentTransactions: AnalyticsTransaction[] = [
  { id: 'TXN-2505124789', sender: 'John Doe', recipient: 'Rahim Uddin', sendCountry: 'United Kingdom', sendFlag: '🇬🇧', receiveCountry: 'Bangladesh', receiveFlag: '🇧🇩', amount: '£500.00', currency: 'GBP', rate: '165.2500', fee: '£3.50', netPayout: '৳62,625.00', status: 'Completed', dateTime: 'May 12, 2025 10:30 AM' },
  { id: 'TXN-2505124788', sender: 'Ahmed Khan', recipient: 'Maria Santos', sendCountry: 'United States', sendFlag: '🇺🇸', receiveCountry: 'Philippines', receiveFlag: '🇵🇭', amount: '$300.00', currency: 'USD', rate: '122.2500', fee: '$2.50', netPayout: '₱36,675.00', status: 'Pending', dateTime: 'May 12, 2025 09:15 AM' },
  { id: 'TXN-2505124787', sender: 'Rashid Ahmed', recipient: 'Sabir Hossain', sendCountry: 'United Kingdom', sendFlag: '🇬🇧', receiveCountry: 'Bangladesh', receiveFlag: '🇧🇩', amount: '£28.00', currency: 'GBP', rate: '165.2500', fee: '£4.00', netPayout: '৳123,937.50', status: 'Completed', dateTime: 'May 12, 2025 08:45 AM' },
  { id: 'TXN-2505124786', sender: 'Imran Hossain', recipient: 'Mohammed Ali', sendCountry: 'Saudi Arabia', sendFlag: '🇸🇦', receiveCountry: 'Bangladesh', receiveFlag: '🇧🇩', amount: 'SAR 1,000.00', currency: 'SAR', rate: '28.5600', fee: 'SAR 8.00', netPayout: '৳30,560.00', status: 'Failed', dateTime: 'May 12, 2025 08:20 AM' },
  { id: 'TXN-2505124785', sender: 'Fatima Ali', recipient: 'Arif Khan', sendCountry: 'United Arab Emirates', sendFlag: '🇦🇪', receiveCountry: 'Pakistan', receiveFlag: '🇵🇰', amount: 'AED 1,250.00', currency: 'AED', rate: '33.2800', fee: 'AED 6.00', netPayout: 'Rs. 162,100.00', status: 'Pending', dateTime: 'May 12, 2025 07:55 AM' },
];

// Top Sending Corridors
export const topSendingCorridors = [
  { corridor: 'UK → Bangladesh', transactions: 5248, volume: '£2,456,780' },
  { corridor: 'USA → Bangladesh', transactions: 4125, volume: '$1,856,230' },
  { corridor: 'UAE → Pakistan', transactions: 2856, volume: 'AED 3,125,450' },
  { corridor: 'Saudi Arabia → Bangladesh', transactions: 1985, volume: 'SAR 2,145,600' },
  { corridor: 'Canada → India', transactions: 1256, volume: 'CAD 856,230' },
];

// Top Agents by Transactions
export const topAgents = [
  { name: 'Abul Hasan', branch: 'Gulshan Branch', avatar: 'AH', transactions: 1256, completionRate: '98.5%' },
  { name: 'Kamal Hossain', branch: 'Uttara Branch', avatar: 'KH', transactions: 985, completionRate: '97.2%' },
  { name: 'Juan Dela Cruz', branch: 'Manila Branch', avatar: 'JD', transactions: 874, completionRate: '96.1%' },
  { name: 'Amit Kumar', branch: 'Mumbai Branch', avatar: 'AK', transactions: 763, completionRate: '95.7%' },
  { name: 'Rashed Alom', branch: 'Sylhet Branch', avatar: 'RA', transactions: 654, completionRate: '95.4%' },
];

// Revenue Summary
export const revenueSummary = [
  { label: 'Total Fees Collected', value: '$425,780' },
  { label: 'Transaction Count', value: '24,752' },
  { label: 'Average Fee per Transaction', value: '$17.20' },
  { label: 'Total Payouts', value: '$4,256,540' },
  { label: 'Net Revenue', value: '$425,780' },
];

// Quick Reports list
export const quickReports = [
  { label: 'Transaction Report', icon: 'doc' },
  { label: 'Cash Pickup Report', icon: 'cash' },
  { label: 'Agent Performance Report', icon: 'agent' },
  { label: 'Revenue & Finance Report', icon: 'revenue' },
  { label: 'Compliance Report', icon: 'compliance' },
  { label: 'Customer Report', icon: 'customer' },
  { label: 'System Activity Report', icon: 'system' },
];

// Report Schedules
export const reportSchedules = [
  { label: 'Daily Transaction Report', sub: 'Every day at 06:00 AM', active: true },
  { label: 'Weekly Summary Report', sub: 'Every Monday at 09:00 AM', active: true },
  { label: 'Monthly Revenue Report', sub: '1st of every month at 10:00 AM', active: true },
  { label: 'Compliance Summary Report', sub: 'Every Friday at 06:00 PM', active: false },
];

// Recent Exports
export const recentExports = [
  { name: 'Transaction_Report_May_12_2025.xlsx', date: 'May 12, 2025 10:30 AM', type: 'xlsx' },
  { name: 'Revenue_Report_April_2025.pdf', date: 'May 12, 2025 09:15 AM', type: 'pdf' },
  { name: 'Agent_Performance_May_2025.xlsx', date: 'May 12, 2025 08:45 AM', type: 'xlsx' },
];

// Country map data (for Transactions by Country - simplified)
export const countryTransactionData = [
  { country: 'Bangladesh', value: 9800, pct: 100 },
  { country: 'India', value: 5200, pct: 53 },
  { country: 'Pakistan', value: 3600, pct: 37 },
  { country: 'Philippines', value: 2400, pct: 24 },
  { country: 'Nigeria', value: 1800, pct: 18 },
  { country: 'Nepal', value: 1200, pct: 12 },
];